### ISSUE TITLE
业务逻辑要如何测试呢？

### ISSUE THREAD

**Issue by kphcdr** [goravel/goravel#11]
我写了一个测试脚本，但是因为测试脚本找不到配置文件，panic掉了

**Comment by hwbrzzl** [comment]
Hi, 什么样的测试脚本？是在根目录写的，还是二级目录写的？运行命令是什么样的？

**Comment by hwbrzzl** [comment]
了解，今天刚更新了 [mock 文档](https://www.goravel.dev/digging-deeper/mock.html)，应该可以解决你的问题，例如在`TestNewUserController` 中，由于调用了 `facades.Log`，所以我们需要 mock facades.Log。
> 以下操作前，go.mod 中请先更新下最新版本 v1.0.5：`github.com/goravel/framework v1.0.5`

根据文档：
<img width="823" alt="image" src="https://user-images.githubusercontent.com/24771476/196197426-8bc9af08-6a92-4b95-a524-e247206593ec.png">
我们可以这样写：
```
import "github.com/goravel/framework/testing/mock"

func TestNewUserController(*testing.T) {
  mock.Log()
  NewUserController()
} 
```
效果如图：
<img width="1828" alt="image" src="https://user-images.githubusercontent.com/24771476/196201090-4f31818e-007d-48f8-aae4-8cceb17d4fa4.png">

**Comment by kphcdr** [comment]
感谢及时反馈，可以解决问题
