### ISSUE TITLE
🐛 [Bug] framework仓库的问题模版不生效

### ISSUE THREAD

**Issue by DevHaoZi** [goravel/goravel#116]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [ ] The problem is generated after upgrading Goravel (问题是在升级 Goravel 后产生的)

### Describe The Problem (描述问题)

framework仓库的问题模版不生效，需要把about字段加回去。

### Reproduction Code (复现代码或截图)

![image](https://user-images.githubusercontent.com/115467771/235450783-1e30e537-eebb-404f-beb1-80a9d1d073bf.png)

### Environment (运行环境)

none

**Comment by hwbrzzl** [comment]
Thanks, fixed.
