### ISSUE TITLE
✨ [Feature] 给所有facades都加上接口注释

### ISSUE THREAD

**Issue by devhaozi** [goravel/goravel#128]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

类似这样，方便开发的时候能直接看到不用频繁去翻文档：
![image](https://github.com/goravel/goravel/assets/115467771/e06966a2-f166-446f-b4d2-1379b47c9f33)
![image](https://github.com/goravel/goravel/assets/115467771/79edfec9-0d9d-4521-915f-1e98c97ef49f)

**Comment by DevHaoZi** [comment]
像carbon这样双语的感觉不错？
![image](https://github.com/goravel/goravel/assets/115467771/91cbd706-d423-4fce-9f8a-480a1c6be087)

**Comment by hwbrzzl** [comment]
I suggest that we only use English in the code for now ~
