### ISSUE TITLE
[BUG] - Creating migration for postgresql doesn't work

### ISSUE THREAD

**Issue by sujit-baniya** [goravel/goravel#13]
I'm trying to create migration using `go run . artisan make:migration` for postgresql, but the SQL it generates does't support postgresql. I changed the driver to postgresql but still the same.

Query generated:
```
CREATE TABLE users (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  created_at datetime(3) DEFAULT NULL,
  updated_at datetime(3) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_users_created_at (created_at),
  KEY idx_users_updated_at (updated_at)
) ENGINE = InnoDB DEFAULT CHARSET = ;
``

**Comment by hwbrzzl** [comment]
Hi, thanks for your issue. Actually, the `database/migrations/20221001000000_create_users_table.up.sql` file is only applicable to Mysql. If you want to use Postgresql, you need to change the default connection in the `config/database.go` file and optimize the `*.sql` file applicable to Postgresql, such as:

```
CREATE TABLE users(
  id int PRIMARY KEY NOT NULL,
  name VARCHAR
);
```

If you have any other questions, please contact me, thanks.

**Comment by sujit-baniya** [comment]
@hwbrzzl I did change the default connection to postgresql. So once the file is generated, I need to change the content of sql for postgresql?

**Comment by hwbrzzl** [comment]
Yup, the template that creating by `go run . artisan make:migration create_users_table` is only applicable to Mysql now. We can generate a Postgresql template based on the default connection in the `config/database.go` file in the future, but unfortunately, we have to change the .sql file manually now.

If you're interested, I'm very glad that you can submit a PR for that. 👍

**Comment by sujit-baniya** [comment]
I have done something similar for migration here https://github.com/sujit-baniya/db/blob/master/migrations/command_new.go

**Comment by hwbrzzl** [comment]
Great, stared. 👍

**Comment by sujit-baniya** [comment]
@hwbrzzl Do you think we could replace current `go-migrate/migrate` with above?

**Comment by hwbrzzl** [comment]
If you can perfect your README, I'm glad to read it first.
