### ISSUE TITLE
✨ [Feature] Use hibiken/asynq replace RichardKnop/machinery

### ISSUE THREAD

**Issue by DevHaoZi** [goravel/goravel#131]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

https://github.com/RichardKnop/machinery library has not been maintained for a long time, and recently there are feedbacks that the queue cannot be stopped after being started. I don’t know if it is the reason for this library. It is recommended to replace it with https://github.com/hibiken/asynq, which is being actively maintained.

**Comment by hwbrzzl** [comment]
Yes, that's great if hibiken/asynq can implement all of the functions.

**Comment by DevHaoZi** [comment]
remove to #153, close it.
