### ISSUE TITLE
🐛 [Bug] 升级 gorm 依赖

### ISSUE THREAD

**Issue by zy108830** [goravel/goravel#137]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

目前 goravel 依赖的 gorm 版本 1.24.6 在执行 Save 方法的时候，期望是 Update 操作，实际上会执行 Update+Create操作

https://github.com/go-gorm/gorm/pull/6149
https://github.com/go-gorm/gorm/issues/6166

gorm 新版本已修复这个问题，希望 goravel 可以同步升级下依赖，谢谢🙏

**Comment by DevHaoZi** [comment]
你好，下次麻烦注意下标题格式。

**Comment by zy108830** [comment]
@DevHaoZi 好的，感谢回复
