### ISSUE TITLE
✨ [Feature] 建议默认加入一个静态文件解析中间件

### ISSUE THREAD

**Issue by lijialong1313** [goravel/goravel#144]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

建议加入一个默认的静态文件中间件，以匹配laravel中放入public的静态文件可以自动解析的直觉。

代码可参考如下：
```
package middleware

import (
	"github.com/goravel/framework/contracts/http"
	"os"
)

//默认静态文件目录
const basePath = "./public"

func PublicMiddleware() http.Middleware {
	return func(ctx http.Context) {
		//请求地址
		path := ctx.Request().Path()
		//匹配文件地址
		filePath := basePath + path
		file, e := os.Stat(filePath)
		if e == nil {
			//文件存在
			if !file.IsDir() {
				//如果文件不是目录，则直接返回文件
				ctx.Response().File(filePath)
				return
			}
		}
		//否则忽略
		ctx.Request().Next()
	}
}

```

**Comment by hwbrzzl** [comment]
Actually, we can add a route to implement this: `facades.Route.Static("static", "./public")`. I'm not sure if we need to add the route as default, what do you think about this, please? cc @DevHaoZi

**Comment by DevHaoZi** [comment]
> Thanks for your suggestion! Actually, we can add a route to implement this: `facades.Route.Static("static", "./public")`. I'm not sure if we need to add the route as default, what do you think about this, please? cc @DevHaoZi

I don't think it is necessary, it might be better to add it to the documentation.

**Comment by hwbrzzl** [comment]
Hi @lijialong1313 You can add the route as shown above, I closed this issue, please comment if you have any question. Thanks for your issue again!
