### ISSUE TITLE
✨ [Feature] 能否设计一个根据模型自动生成迁移的参数

### ISSUE THREAD

**Issue by lijialong1313** [goravel/goravel#145]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

目前生成模型后，需要自行生成sql迁移文件

能否参考laravel的方式，通过artisan make:model User -m的参数自动生成migration文件。或者增加一个命令，通过artisan make:migration --model=User这种形式

或者可以参考gorm本身的AutoMigrate方式：https://gorm.io/zh_CN/docs/migration.html

**Comment by hwbrzzl** [comment]
Yes, good idea, we can implement it like Laravel, but we need to deal with the differences between different drivers, I think AutoMigrate doesn't suitable for Goravel, it's so different from Laravel.

Please create a PR if you are interested in this.

**Comment by DevHaoZi** [comment]
> Yes, good idea, we can implement it like Laravel, but we need to deal with the differences between different drivers, I think AutoMigrate doesn't suitable for Goravel, it's so different from Laravel.
> 
> Please create a PR if you are interested in this.

可以试着参考`https://github.com/summerblue/gohub/tree/G02_1.19/pkg/migrate`的实现，感觉不错。

**Comment by hwbrzzl** [comment]
> > Yes, good idea, we can implement it like Laravel, but we need to deal with the differences between different drivers, I think AutoMigrate doesn't suitable for Goravel, it's so different from Laravel.
> > Please create a PR if you are interested in this.
> 
> 可以试着参考https://github.com/summerblue/gohub/tree/G02_1.19/pkg/migrate的实现，生成的迁移https://github.com/summerblue/gohub/tree/G02_1.19/database/migrations感觉不错。

The migration files seem so different with Laravel, User needs to learn a new rule on it, so I think maybe it's not very good for us ~

**Comment by devhaozi** [comment]
#280
