### ISSUE TITLE
[Question] - How can I make some service providers load only after configs are full loaded?

### ISSUE THREAD

**Issue by sujit-baniya** [goravel/goravel#15]
Great work on the package. I'm trying to extend and implement some features and wanted to load some of the service providers only after the configs are full loaded.

Can you please suggest some ways to achieve it?

Forked repo: https://github.com/sujit-baniya/goravel

**Comment by hwbrzzl** [comment]
Adding a provider here is ok. Do you have any specific problems?
<img width="797" alt="image" src="https://user-images.githubusercontent.com/24771476/197929235-de1e8f88-e1f5-4835-b3cb-3b076dd90aa8.png">

**Comment by sujit-baniya** [comment]
Yes I've a problem doing something like this

![image](https://user-images.githubusercontent.com/4959215/197942981-99b61350-e93e-42aa-aeab-ba58033bbb26.png)

**Comment by sujit-baniya** [comment]
With some changes in API, I made it work.

1) Moved "providers" as separate "Providers()" function
2) Add "Providers" in foundation.Application and called "Providers()"function on the field
3) Moved "config.Boot()" above "app.Boot()"

**Comment by hwbrzzl** [comment]
> Yes I've a problem doing something like this
> 
> ![image](https://user-images.githubusercontent.com/4959215/197942981-99b61350-e93e-42aa-aeab-ba58033bbb26.png)

Yes, you are right, at this time, `facades.Config` has not been initialized. You need to use `config.Env` in `config/*.go` file. Happy to know that you had resolved this problem. 👍
