### ISSUE TITLE
✨ [Feature] Reduce third-party packages use

### ISSUE THREAD

**Issue by devhaozi** [goravel/goravel#154]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

At present, some packages are not necessary. for example :

`github.com/manifoldco/promptui`, `github.com/jordan-wright/email`, `github.com/opentracing/opentracing-go`, `github.com/pkg/errors`, `github.com/rifflock/lfshook`, `github.com/rs/cors`, `github.com/unrolled/secure`, 

Try to gradually replace them with self-implementation in the future.This will help prevent unknown bugs and vulnerability risks and reduce package size.

**Comment by DevHaoZi** [comment]
点名`github.com/RichardKnop/machinery`，引入的包那叫一个多，重构给它换了。
![image](https://github.com/goravel/goravel/assets/115467771/caed152c-435b-4b02-9aca-2bb3255a0327)

**Comment by DevHaoZi** [comment]
Plan to replace json package `encoding/json` to `github.com/bytedance/sonic,` it's more faster and compatible with `encoding/json`.
