### ISSUE TITLE
go run . artisan key:generate无效

### ISSUE THREAD

**Issue by wingofsky** [goravel/goravel#17]
goravel/framework v1.3.1

#### 执行过程
```shell
(base) ➜  gorav go run . artisan key:generate
# gorm.io/driver/sqlserver
../../../pkg/mod/gorm.io/driver/sqlserver@v1.3.2/sqlserver.go:90:22: cannot convert 0 (untyped int constant) to *int
../../../pkg/mod/gorm.io/driver/sqlserver@v1.3.2/sqlserver.go:95:39: cannot use limit.Limit (variable of type *int) as type int in argument to strconv.Itoa
```

.env 文件没有生成APP_KEY

**Comment by hwbrzzl** [comment]
Hi, 感谢反馈。请问 goravel 拉下来后有新增什么逻辑么？.env 文件内容方便发出来看下么？

**Comment by wingofsky** [comment]
> Hi, 感谢反馈。请问 goravel 拉下来后有新增什么逻辑么？.env 文件内容方便发出来看下么？

全新的项目

按照：https://www.goravel.dev/zh/getting-started/installation.html

这个在跑，跑到go run . artisan key:generate报错

变动只把mod里 go 1.18 改成了 go 1.19，没动过其他的

**Comment by hwbrzzl** [comment]
收到，thanks，我这里试一下

**Comment by hwbrzzl** [comment]
Hi @wingofsky , 我用以下步骤未能复现你的问题：
1. 使用 docker 搭建 go 1.19 环境;
2. `git pull git@github.com:goravel/goravel.git goravel`；
3. 修改 go.mod 中 `go 1.18` -> `go 1.19`
4. `cp .env.example .env`;
5. `go mod tidy`;
6. `go run . artisan key:generate`;
<img width="645" alt="image" src="https://user-images.githubusercontent.com/24771476/199926549-d93b4f26-73be-4a88-ac8a-377f5de0ae4c.png">

**还请回复更多信息来帮助排查问题：**

1. 你的运行环境时 windows 还是 MacOS？
2. go version 输出的具体信息是什么？
3. 你的操作步骤与我上述步骤是否有差异？差异是什么？

**Comment by hwbrzzl** [comment]
Hi, 你是将 Goravel 同其他目录一起放到 go.work 了么？如果不使用 go.work 根据你现在的步骤运行是否正常呢？另外我看你的截图中显示你是运行在「(base)」下，请问这是一个容器环境吗？

**Comment by wingofsky** [comment]
> 

不是容器
我放到go.work外，就可以了，谢谢！

![image](https://user-images.githubusercontent.com/1725695/200163332-ae94794a-5f0d-4c7c-b6ba-feb2e09f0c65.png)

**Comment by hwbrzzl** [comment]
Great, 碰到任何问题欢迎 Issues, PR

**Comment by wingofsky** [comment]
> Hi @wingofsky , 我用以下步骤未能复现你的问题：
> 
> 1. 使用 docker 搭建 go 1.19 环境;
> 2. `git pull git@github.com:goravel/goravel.git goravel`；
> 3. 修改 go.mod 中 `go 1.18` -> `go 1.19`
> 4. `cp .env.example .env`;
> 5. `go mod tidy`;
> 6. `go run . artisan key:generate`;
> 
> <img alt="image" width="645" src="https://user-images.githubusercontent.com/24771476/199926549-d93b4f26-73be-4a88-ac8a-377f5de0ae4c.png">
> 
> **还请回复更多信息来帮助排查问题：**
> 
> 1. 你的运行环境时 windows 还是 MacOS？
> 2. go version 输出的具体信息是什么？
> 3. 你的操作步骤与我上述步骤是否有差异？差异是什么？

MACOS
步骤如图 
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/1725695/200162224-2c03104f-0920-4b06-a098-6853447e307c.png">

其中有两次错误是我忘记把目录放到go.work里了（且第二次写错路径了）
