### ISSUE TITLE
✨ [Feature] Add Minutes, hours, days methods for facades.Schedule()

### ISSUE THREAD

**Issue by hwbrzzl** [goravel/goravel#177]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

`Minutes`: Run every N minutes
`Hours`: Run every N hours
`Days`: Run every N days

**Comment by narad-muni** [comment]
> 

Can I take up this task?, If yes, I am on it.

**Comment by hwbrzzl** [comment]
Sure, please, thanks!

**Comment by hwbrzzl** [comment]
Hi @narad-muni Are you still working on this, please?
