### ISSUE TITLE
✨ [Feature] Add Collections module

### ISSUE THREAD

**Issue by hwbrzzl** [goravel/goravel#179]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

Just like: https://laravel.com/docs/10.x/collections

**Comment by zKoz210** [comment]
https://github.com/samber/lo

**Comment by Kamandlou** [comment]
Something like this: https://github.com/goravel/framework/pull/456?

**Comment by Kamandlou** [comment]
@hwbrzzl

**Comment by hwbrzzl** [comment]
Sorry, I missed the first message, checking.
