### ISSUE TITLE
怎么用gorm原生功能

### ISSUE THREAD

**Issue by netwu** [goravel/goravel#19]
想使用gorm原生的Clauses

**Comment by hwbrzzl** [comment]
Hi，目前可以临时使用下面代码获取 gorm 实例，后续对于 Clauses 的官方支持还需要调研一下。使用框架过程中有任何问题欢迎随时沟通 👍 
```
import "github.com/goravel/framework/database"

gorm, _ := database.NewGormInstance("mysql")
```

**Comment by hwbrzzl** [comment]
Please reopen this issue if you have any other questions.

**Comment by wingofsky** [comment]
@hwbrzzl Gorm自带的AutoMigrate对于我来说很好用（比Laravel简单），期望后续可以有类似的实现

**Comment by ihipop** [comment]
什么时候能升级到 gorm 2.0 呢

**Comment by hwbrzzl** [comment]
@ihipop 目前已经是 2.0 了，可以参考这个文档：https://gorm.io/docs/v2_release_note.html
