### ISSUE TITLE
✨ [Feature] 建议facades.Orm(), 新增 AutoMigrate

### ISSUE THREAD

**Issue by yueqing2617** [goravel/goravel#191]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

新增 AutoMigrate, 可选用迁移功能
contracts/database/orm/orm.go:
```
type Orm interface {
	...
	AutoMigrate(values ...any) error
}
```
database/orm.go:
```
func (r *OrmImpl) AutoMigrate(values ...any) error {
	//TODO implement me
	db := r.Query().(*databasegorm.QueryImpl)

	return db.Instance().AutoMigrate(values...)
}
```

**Comment by hwbrzzl** [comment]
Hi @yueqing2617 Thanks for your feedback, `AutoMigrate` is so different from Laravel migration, and we think `AutoMigrate ` is not very safe and graceful, so we don't have a plan to implement this feature now.

**Comment by DevHaoZi** [comment]
Close, please reopen if necessary.
