### ISSUE TITLE
缓存将怎么设计？会覆盖哪些场景？

### ISSUE THREAD

**Issue by yk133** [goravel/goravel#2]
缓存将怎么设计？会覆盖哪些场景？

**Comment by hwbrzzl** [comment]
会类似 Laravel 的多驱动设计，前期的话默认只支持 redis，自己可以写扩展。缓存模块这几天会发布一版。

**Comment by hwbrzzl** [comment]
> 缓存将怎么设计？会覆盖哪些场景？

会类似 Laravel 的多驱动设计，前期的话默认只支持 redis，自己可以写扩展。缓存模块这几天会发布一版。
