### ISSUE TITLE
✨ [Feature] The HTTP middleware can be move to goravel/http-middleware

### ISSUE THREAD

**Issue by hwbrzzl** [goravel/goravel#204]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

The existing HTTP middleware looks very generic, and can be used in gin or fiber, just `cors` needs a bit of modification: change `gin` to `net/http`. So I think we can remove them from goravel/gin and create a new repository: goravel/http-middleware after [the PR](https://github.com/goravel/framework/pull/198) is merged.

**Comment by hwbrzzl** [comment]
What do you think about this, please? cc @DevHaoZi

**Comment by DevHaoZi** [comment]
> What do you think about this, please? cc @DevHaoZi

No Problem.

**Comment by hwbrzzl** [comment]
There is [a PR](https://github.com/goravel/framework/pull/232) for gzip and brotli middleware, we need to add a configuration to control whether to use the middleware.

If we deal with this issue, there will be three places containing HTTP middleware: goravel/framework, goravel/http-middleware, goravel/gin(some specific middleware for gin, there is no this now, but maybe have in the future), they are so dispersed. 

Maybe there is no reason to add a new repository in this situation, we can leave the current middleware in goravel/framework first, and I'll optimize the CORS middleware to remove the gin dependency, so [this PR](https://github.com/goravel/framework/pull/198) doesn't need to remove the middleware anymore.

What do you think about this, please? cc @DevHaoZi
