### ISSUE TITLE
🐛 [Bug] Trying to lazy eager load relation is not working

### ISSUE THREAD

**Issue by Marian0** [goravel/goravel#205]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [ ] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

MacOS

### Golang Version (Go 版本)

1.19.x

### Goravel Version (Goravel 版本)

1.12.4

### Describe The Problem (描述问题)

While trying to get relations with Gorm using the `Load` method I get an error. I double checked the model definitions but there's no luck. I tried to debug goravel framework codebase but it's too complex for me to understand yet..

Here's the code i'm  using as an example

```go
type BlogPost struct {
	ID uuid.UUID `gorm:"primaryKey;type:uuid;default:uuid_generate_v4()"`
	orm.Timestamps
	orm.SoftDeletes
	//
	Title                   *string
	
	UserID *uuid.UUID
	// relations
	User *User `gorm:"foreignKey:UserID;references:ID"`
}

type User struct {
	ID   uuid.UUID `gorm:"primaryKey;type:uuid;default:uuid_generate_v4()"`
	Name string
}
```

### Reproduction Code (复现代码或截图)

on controller:

```go
if err := facades.Orm().Query().Create(&blogPost); err != nil {
		helpers.RespondError(ctx, http.StatusInternalServerError, err.Error())
		return
	}

	// load relations
	err = facades.Orm().Query().Load(&blogPost, "User")

	log.Println(err) 

```

At 	log.Println(err)  I'm getting:

```
2023/06/30 17:12:37 id cannot be empty

```

This came from:

```go/pkg/mod/github.com/goravel/framework@v1.12.4/database/gorm/query.go:288```

**Comment by hwbrzzl** [comment]
Hi @Marian0 Have some questions:
1. What's your DB?
2. Could you please reply your table SQL here?
3. What's the uuid package? google/uuid?
4. I guess it's caused by uuid.UUID type.

**Comment by Marian0** [comment]
Hi @hwbrzzl 

1) I tested this using both Postgres and Mysql - In postgres using `gen_random_uuid()` and also using BeforeCreate orm lifecycle (as the attached example) 
2) https://github.com/Marian0/todo-app-goravel/tree/sandbox/example-eager-loading-bug
3) I'm currently using `github.com/google/uuid`
4) Yes, you are right - The uuid type makes [this condition ](https://github.com/goravel/framework/pull/226/files#diff-385f411c58779199cd9530e6675be32f3332a63a70f9e3ad392e73882ab042a9R42) to be always true resulting on a nil return which finally results on the `id cannot be empty` error.

**Comment by hwbrzzl** [comment]
Thanks, I'll take a look.

**Comment by hwbrzzl** [comment]
I think [this PR](https://github.com/goravel/framework/pull/226) is right, and your model also needs to have a modification as shown below. Could you please add a unit test for this issue in your PR?
<img width="299" alt="image" src="https://github.com/goravel/goravel/assets/24771476/1038a64c-8fe7-41bd-91a6-b64782025570">

**Comment by Marian0** [comment]
hey @hwbrzzl, you are right about the gorm annotations. Thanks for the feedback.

I've pushed some unit tests, please let me know any thoughts/feedback.

Happy to contribute here if you have a better idea.

💪
