### ISSUE TITLE
✨ [Feature] Some optimizations for goravel/gin repository

### ISSUE THREAD

**Issue by hwbrzzl** [goravel/goravel#206]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

1. We can remove the `gin_` prefix for all files;
2. Missing route/gin_group_test.go:535::TestThrottle
3. Missing route/gin_group_test.go:222::Any Options
4. Change `GinRoute` to `Route`
5. Need to initialize `RateLimiterFacade`: https://github.com/goravel/gin/blob/a5ba5540bd87de1bdbe042e2ee800eace27a7598/service_provider.go#L23C2-L23C36

**Comment by DevHaoZi** [comment]
Finished, the tests of Throttle middleware and CORS middleware will be moved to the http-middleware repository for testing.
