### ISSUE TITLE
✨ [Feature] Gzip compression support 

### ISSUE THREAD

**Issue by Marian0** [goravel/goravel#208]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

Hey guys,

I'm wondering how can we use a gzip middleware so the http request i want can be gzipped.

I tried to use this package https://github.com/gin-contrib/gzip

But i'm not sure how to transform from `gin.HandlerFunc` to our middleware handler which accepts a `middlewares ...contractshttp.Middleware`

Would be great also to include some other compression algorithms like `brotli`

**Comment by hwbrzzl** [comment]
Hi @Marian0 Thanks for your issue, we have an example for changing `gin.HandlerFunc` to `httpcontract.Middleware`: https://github.com/goravel/framework/blob/master/http/middleware/cors.go.

For https://github.com/gin-contrib/gzip, I wonder if we can implement an original `httpcontract.Middleware` through it(not `gin.HandlerFunc`), like below:

<img width="1918" alt="image" src="https://github.com/goravel/goravel/assets/24771476/68e5aca2-e029-45a8-9e83-ce8cc2786f08">

Anyway, we can implement this feature after [this PR](https://github.com/goravel/framework/pull/198) is merged.

**Comment by DevHaoZi** [comment]
I don't think we need this feature. In most cases, Goravel will work behind Nginx as a backend. Enable Gzip or Brotli on Nginx is more common practice.

**Comment by devhaozi** [comment]
It seems that this feature is difficult to implement directly in the framework and needs to be coordinated with the routing driver (gin or fiber) through middleware.

There is a example to add a gin middleware in goravel:
```go
package middleware

import (
	"github.com/gin-contrib/static"
	contractshttp "github.com/goravel/framework/contracts/http"
	"github.com/goravel/gin"

	"panel/app/services"
)

func Static() contractshttp.Middleware {
	return func(ctx contractshttp.Context) {
		static.Serve(services.NewSettingImpl().Get("entrance", "/"), static.LocalFile("/www/panel/public", false))(ctx.(*gin.Context).Instance())

		ctx.Request().Next()
	}
}


```
