### ISSUE TITLE
✨ [Discuss] Discussion of Http service startup

### ISSUE THREAD

**Issue by flc1125** [goravel/goravel#209]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

I recommend that Http be started as a command on Console, rather than asynchronously as the main.go main entry. Here's why:

- While I will also start this service when I execute other commands and do not need the Http service
- Go the Http service, more like https://github.com/laravel/octane, Laravel official start is also based on the command line.

> PS: In addition, independent commands are also recommended, such as timing service.

**Comment by hwbrzzl** [comment]
Hi @flc1125 Thanks for your issue, could you please give an example for "a command"?

**Comment by flc1125** [comment]
> Hi @flc1125 Thanks for your issue, could you please give an example for "a command"?

OK, give me some time.

I'm going to get busy...

**Comment by hwbrzzl** [comment]
Sure, just do it when you have time. 👍

**Comment by flc1125** [comment]
> Hi @flc1125 Thanks for your issue, could you please give an example for "a command"?

Example: https://github.com/goravel/goravel/pull/210

这仅是为一个示例，代码逻辑存在问题，无法正确执行，主要是希望表达的含义。

> 待讨论结束，这个 PR 可以随时关闭

----

**思路说明：**

- 我定义了一个基于 `Console` 的 `Kernel`，用于作为整个应用启动的控制台。
	- 这里包含了所有的命令，当然还包括了 Http.Server 启动命令，假设这个命令是`server:start`
	- 启动台实现了应用**预启动**、**处理**、**退出进程**的实现
	- 同时包含了捕获异常的处理
- 我将上面的启动，设置在 `main.go`，并以此作为整个应用的入口文件。所有的逻辑将从这里启动。
- 所以未来我的执行方式，可能是：
	- `go run main.go` 我可以看到所有的命令行以及命令的介绍
	- `go run main.go server:start` 我可以启动一个 Http 服务
	- ……

----

如上是我的想法

**Comment by flc1125** [comment]
**关于 https://github.com/goravel/framework/pull/231 的说明：**

- 这个方法是为了这部分的实现 https://github.com/pr-fork/goravel/blob/app-kernel-draft/app/console/kernel.go#L38-L42
- Panic只是一个默认的 recovery 方式
- 当然我们可以继续完善支持如 Log，Event 等待

**Comment by flc1125** [comment]
**关于 Kernel 控制台的补充说明：**

- 思路来源：https://github.com/laravel/framework/blob/10.x/src/Illuminate/Contracts/Console/Kernel.php
- Http Kernel：Go 相较于 PHP（Laravel）的传统启动 Http 的方式有些不一样，`Laravel` 将 Http 入口设定在 `public/index.php` 是为了适应传统的 FPM 架构。但基于 Go 的常驻命令，它更符合 https://github.com/laravel/octane 的启动方式。
- 关于三个实现的说明：
	- `Bootstrap()`：我们可以在这里实现一些如 Application 的启动，一些其他需要预启动的逻辑
	- `Handle()`: 是整个应用启动的核心逻辑，结合我们的框架，我推荐启动 Console.Run() 
	- `Terminate()`: 当进程退出时，我们可处理的逻辑，如：关闭连接、文件刷盘等。如果我们要实现这个功能，那意味着我们的 `ServicePrivoder` 需要补充 `Terminate()` 的实现。

**Comment by hwbrzzl** [comment]
Thanks for your idea! 

Should we need to run another process(or command) if we want to run the schedule module at the same time?

**Comment by flc1125** [comment]
> Thanks for your idea!
> 
> Should we need to run another process(or command) if we want to run the schedule module at the same time?

看我们是倾向哪方面吧。**`Go 风格` Or `Laravel 风格`？**

----

我们先大概了解下如下两个项目的做法（但不一定全面）：

|生态|启动|优势|不足|
|----|----|----|----|
|Hyperf|整个服务由一个命令`php bin/hyperf.php start` 启动，期间涉及到如：定时、队列等均以另外创建 **子进程** 的形式进行启动。|一个命令，启动所有服务|1、当存在多节点集群部署时，需考虑部分服务单节点启动问题，如定时可能只需要一个节点启动即可。<br/>2、……|
|Laravel|Http、定时、队列均以不同的命令各自启动|依托于独立进程，可维护性相对较高|需要一定的部署能力，避免遗漏|

----

如上，个人认为 Go 领域的启动，更倾向于 Hyperf 形式。区别在于以**异步协程**的形式进行启动。

**Comment by hwbrzzl** [comment]
Thanks, this's so detailed.

I think the above two ways are already supported in goravel, the second way is the default way, and users can define a command by themselves to implement the first way.

About Schedule only needs to run in one Pod, we had implemented it in [this PR](https://github.com/goravel/framework/pull/227), but haven't released a new version.

**Comment by flc1125** [comment]
Nice, looking forward to your new version release.

**Comment by flc1125** [comment]
I will close this discussion and if we have a new discussion, we can reopen it.  😁😁
