### ISSUE TITLE
[QUESTION] - How can I implement authentication using different approaches?

### ISSUE THREAD

**Issue by sujit-baniya** [goravel/goravel#21]
Can you please suggest how can I implement different auth approaches: `session`, `api-key`, `jwt`?

I see that currently it has just jwt authentication

**Comment by hwbrzzl** [comment]
Hi, thanks for your question, we can do it following the steps as shown below:

`goravel/goravel`
1. Add a new guard and a new driver name in the `config/auth.go` file;

`goravel/framework`
1. Add the new driver in the `auth` folder, the driver needs to implement the `contracts/auth/auth.go` interface;
2. Implement the switch driver logic in the `auth/application.go` file;
