### ISSUE TITLE
🐛 [Bug] how to send cookie responses..

### ISSUE THREAD

**Issue by rajuaryan21** [goravel/goravel#211]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [ ] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

Linux

### Golang Version (Go 版本)

1.18.x

### Goravel Version (Goravel 版本)

1.12.5

### Describe The Problem (描述问题)

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

I am trying to implement JWT tokens for browser-based sessions using cookies as I am building a stateful application and templates are being parsed by Golang.

I could not find a way to send a cookie response back to the client. is there something I missed in the doc or cookie response is not implemented yet?

Cookie serves many purposes in my app including tracking and behaviors of our customers, not just login. So, can anybody tell me how to implement cookie responses in Goravel?

Thank you for this awesome project.

### Reproduction Code (复现代码或截图)

I am trying to implement JWT tokens for browser-based sessions using cookies as I am building a stateful application and templates are being parsed by Golang.

I could not find a way to send a cookie response back to the client. is there something I missed in the doc or cookie response is not implemented yet?

Cookie serves many purposes in my app including tracking and behaviors of our customers, not just login. So, can anybody tell me how to implement cookie responses in Goravel?

Thank you for this awesome project.

**Comment by hwbrzzl** [comment]
Hi @rajuaryan21 sorry for the late, we have an example for this feature: https://github.com/goravel/example#jwt-middleware

**Comment by rajuaryan21** [comment]
That's an example of using middleware.. but how do we send HTTP cookie along with JSON or HTML responses.?

I had to use net/http package to create cookie and send as a response.

nethttp.SetCookie(ctx.Response().Writer(), &nethttp.Cookie{
		Name:  "token",
		Value: token,
	})

	response = map[string]any{
		"status":  true,
		"message": "Login successful.",
	}
	ctx.Response().Success().Json(response)

like this... but is this correct way to use?

**Comment by hwbrzzl** [comment]
I think you can do this like below:
```
ctx.Response().Header("Authorization", token)
```
<img width="1516" alt="image" src="https://github.com/goravel/goravel/assets/24771476/e2442e06-f129-4513-a4c8-9eb9c17d6173">

**Comment by hwbrzzl** [comment]
I closed this issue first, feel free to reopen it if you need.

**Comment by OrkhanAlikhanov** [comment]
I think it would better to have an example in the docs regarding how to deal with cookies. I had to spend good chunk of my time investigating how to do this properly. 

```go
import netHttp "net/http"

/// Reading cookie
cookie, err := ctx.Request().Origin().Cookie("session")

/// Setting cookie
cookie := &netHttp.Cookie{
	Name:     "session",
	Value:    url.QueryEscape(token),
	Secure:   true,
	HttpOnly: true,
	Expires:  time.Now().Add(time.Duration(ttl) * time.Minute),
}
ctx.Response().Header("Set-Cookie", cookie.String())
```
