### ISSUE TITLE
🐛 [Bug] Unable to validate float values

### ISSUE THREAD

**Issue by Marian0** [goravel/goravel#212]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [ ] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

MacOS

### Golang Version (Go 版本)

1.19.x

### Goravel Version (Goravel 版本)

1.12.5

### Describe The Problem (描述问题)

While building a sample API that accepts some float as parameter, I'm not allowed to perform float validation.

I get some marshalling errors while i try to send amount as a string, for example:

## Body:
```json
{
    "date": "2023-07-14T09:30:00+03:00",
    "amount": "20"
}
```

## Error response:
```
{
    "errors": "json: cannot unmarshal string into Go struct field SaveRequest.amount of type float64"
}
```

## Console
there's some weird error on the terminal as well coming from `goravel-framework/http/gin_request.go` line 364 `return nil, fmt.Errorf("decode json [%v] error: %v", string(bodyBytes), err)`

```
time="2023-07-14T17:02:16-03:00" level=error msg="decode json [] error: unexpected end of JSON input"
time="2023-07-14T17:02:16-03:00" level=error msg="<nil>" ## unwrapped error
```

### Reproduction Code (复现代码或截图)

```go
package expense

import (
	"github.com/goravel/framework/contracts/http"
	"github.com/goravel/framework/contracts/validation"
)

type SaveRequest struct {
	Date             string   `json:"date"`
	Amount           float64  `json:"amount"`
}

func (r *SaveRequest) Authorize(ctx http.Context) error {
	return nil
}

func (r *SaveRequest) Rules(ctx http.Context) map[string]string {
	return map[string]string{
		"date":              "required|date",
		"amount":            "required|numeric|gt:0",
	}
}

func (r *SaveRequest) Messages(ctx http.Context) map[string]string {
	return map[string]string{}
}

func (r *SaveRequest) Attributes(ctx http.Context) map[string]string {
	return map[string]string{}
}

func (r *SaveRequest) PrepareForValidation(ctx http.Context, data validation.Data) error {
	return nil
}

```

**Comment by hwbrzzl** [comment]
Yes, the `amount` in the body must be a float type.
```
{
    "date": "2023-07-14T09:30:00+03:00",
    "amount": 20
}
```

**Comment by Marian0** [comment]
@hwbrzzl wouldn't suppose to be the validator responsable for type checking ? If I as a user send an `amount` as a string i expect to receive some error like `amount must be float` but currently having this message:

``` 
json: cannot unmarshal string into Go struct field SaveRequest.amount of type float64
```

wdyt?

**Comment by hwbrzzl** [comment]
Oh, this error, yes, but we don't have `numeric` rule, I think you can use `number`, you can get all rules here: https://www.goravel.dev/the-basics/validation.html#available-validation-rules

**Comment by hwbrzzl** [comment]
I closed this issue first, feel free to reopen it if you need.

**Comment by hwbrzzl** [comment]
Hey @Marian0  What's your github name, please?
