### ISSUE TITLE
🐛 [Bug] 

### ISSUE THREAD

**Issue by rajuaryan21** [goravel/goravel#214]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [ ] The problem can be stably reproduced (这个问题可以被稳定复现)
- [ ] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

Linux

### Golang Version (Go 版本)

1.18.x

### Goravel Version (Goravel 版本)

1.12.0

### Describe The Problem (描述问题)

is there any file-based driver for cache implementation? I couldn't find any doc. This one is an essential requirement for caching your data.

### Reproduction Code (复现代码或截图)

is there any file-based driver for cache implementation? I couldn't find any doc. This one is an essential requirement for caching your data.

**Comment by hwbrzzl** [comment]
We support memory and Redis drivers now, I wonder what's your requirement for using the file driver?

**Comment by hwbrzzl** [comment]
I closed this issue first, feel free to reopen it if you need.
