### ISSUE TITLE
✨ [Feature] improve validation functions

### ISSUE THREAD

**Issue by devhaozi** [goravel/goravel#216]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

When using regular expressions with `|` sign, the validation will parse it to a new rule. See gookit/validate#70.

In laravel, validation can be use like:
```
$input = $this->validate($request, [
    'time' => ['required', 'regex:/^((\*|\d+|\d+-\d+|\d+\/\d+|\d+-\d+\/\d+|\*\/\d+)(\,(\*|\d+|\d+-\d+|\d+\/\d+|\d+-\d+\/\d+|\*\/\d+))*\s?){5}$/'],
    'limit' => 'required|integer',
    'page' => 'required|integer',
]);
```
to aviod this problem.

**Comment by DevHaoZi** [comment]
How do you think it should be resolved? 
cc @hwbrzzl

**Comment by hwbrzzl** [comment]
Can we use [Custom Validation Rules](https://www.goravel.dev/the-basics/validation.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%AA%8C%E8%AF%81%E8%A7%84%E5%88%99) to deal with this?

**Comment by DevHaoZi** [comment]
> Can we use [Custom Validation Rules](https://www.goravel.dev/the-basics/validation.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%AA%8C%E8%AF%81%E8%A7%84%E5%88%99) to deal with this?

It can be solved, but think it is not the best way to add a lot of custom rules.

**Comment by hwbrzzl** [comment]
Yes, I think so. Maybe we can do a layer of special handling when passing `regex`: Change `regex` in the validate string to `v.AddRule("name", "regex", "^(PCAP|DOC)$")`?

**Comment by hwbrzzl** [comment]
Duplicated with https://github.com/goravel/goravel/issues/285
