### ISSUE TITLE
🐛 [Bug] Array validation panic

### ISSUE THREAD

**Issue by zKoz210** [goravel/goravel#219]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [ ] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

MacOS

### Golang Version (Go 版本)

1.20.x

### Goravel Version (Goravel 版本)

1.12.5

### Describe The Problem (描述问题)

I'm trying to make a request and I'm getting this error:
```
http: panic serving 127.0.0.1:51845: runtime error: invalid memory address or nil pointer dereference
goroutine 22 [running]:
net/http.(*conn).serve.func1()
        /opt/homebrew/opt/go/libexec/src/net/http/server.go:1854 +0xb0

```

### Reproduction Code (复现代码或截图)

```go
func (r *UserController) Show(ctx http.Context) {
	validator, _ := ctx.Request().Validate(map[string]string{
		"clinics": "array",
	})

	ctx.Response().Success().Json(http.Json{
		"Errors": validator.Errors().All(),
		"Data":  ctx.Request().All(),
	})
}
```

```json
{
    "clinics": [
        {
            "id": 611
        }
    ]
}
```

**Comment by hwbrzzl** [comment]
Actually, you can't call `validator.Errors().All()` directly, because the validation is passed and `validator.Errors()` is nil, you need judge `if validator.Fails()` first.

**Comment by zKoz210** [comment]
thanks and sorry for my mistake <3
