### ISSUE TITLE
✨ [Feature] Support validating nested array input (each element of an array)

### ISSUE THREAD

**Issue by zKoz210** [goravel/goravel#221]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

Without the current feature, it is quite difficult to implement complex nesting and validate it

Docs: https://laravel.com/docs/10.x/validation#validating-nested-array-input

```go
validator, _ := ctx.Request().Validate(map[string]string{
	"clinics":      "required|array",
	"clinics.*.id": "required|int",
	"clinics.*.name": "required|string",
})
```

```json
{
    "clinics": [
        {
            "id": 611,
            "name": "Clinic 1"
        }
    ]
}
```

**Comment by hwbrzzl** [comment]
The validation module is implemented by `github.com/gookit/validate`, it doesn't support this rule, maybe we can use another package to support this rule in the future.

**Comment by zKoz210** [comment]
this seems to be supported by the package: https://github.com/gookit/validate/releases/tag/v1.5.0

Goravel:
```
	facades.Route().Post("/", func(ctx http.Context) {
		validator, _ := ctx.Request().Validate(map[string]string{
			"clinics":        "required|array",
			"clinics.*.id":   "required|int",
			"clinics.*.name": "required|string",
		})

		if validator.Fails() {
			ctx.Response().Status(422).Json(http.Json{
				"result": validator.Errors().All(),
			})

			return
		}

		ctx.Response().Success().Json(http.Json{
			"result": ctx.Request().All(),
		})

		//ctx.Response().Json(http.StatusOK, http.Json{
		//	"Hello": "Goravel",
		//})
	})
```

Request:
```
{
    "clinics": [
        {
            "id": 1234,
            "name": "Clinic 1"
        },
         {
            "id": 123,
            "name": "Clinic 12222"
        }
    ]
}
```

Response:
```
{
    "result": {
        "clinics.*.id": {
            "int": "clinics.*.id value must be an integer"
        }
    }
}
```

gookit/validation example (OK):

```
	m := map[string]any{
		"clinics": []map[string]any{
			{
				"id":   123213,
				"name": "Clinic 1",
			},
			{
				"id":   123213,
				"name": "Clinic 1",
			},
		},
	}

	v := validate.Map(m)

	v.StringRule("clinics", "required|array")
	v.StringRule("clinics.*.id", "required|int")
	v.StringRule("clinics.*.name", "required|string")

	if v.Validate() { // validate ok
		safeData := v.SafeData()

		fmt.Println("Validation OK:")
		fmt.Println(safeData)
	} else {
		fmt.Println(v.Errors)       // all error messages
		fmt.Println(v.Errors.One()) // returns a random error message text
	}
```

Result:
```
Validation OK:
map[clinics:[map[id:123213 name:Clinic 1] map[id:123213 name:Clinic 1]] clinics.*.id:[123213 123213] clinics.*.name:[Clinic 1 Clinic 1]]

```

**Comment by hwbrzzl** [comment]
Thanks, good catch, just found out about this, I'll make a test later.

**Comment by hwbrzzl** [comment]
Yes, we can use this rule now, the `github.com/gookit/validate` package upgraded in the master branch, will be released on v1.13.0. Thanks for your catch!

**Comment by zKoz210** [comment]
@hwbrzzl I tested more cases and validation works very strange

100% there is a problem with the types, I don't understand what could be the problem

Code:

```go
facades.Route().Post("/", func(ctx http.Context) {
		validator, _ := ctx.Request().Validate(map[string]string{
			"user_id": "required|int",
		})

		if validator.Fails() {
			ctx.Response().Status(422).Json(http.Json{
				"result": validator.Errors().All(),
			})

			return
		}

		ctx.Response().Success().Json(http.Json{
			"result": ctx.Request().All(),
		})
	})
```

Request:

```json
{
    "user_id": 11234
}
```

Result:

```json
{
    "result": {
        "user_id": {
            "int": "user_id value must be an integer"
        }
    }
}
```

**Comment by zKoz210** [comment]
debug

![image](https://github.com/goravel/goravel/assets/28255085/744126cb-f39f-4537-9d17-0ed70e25d809)

**Comment by hwbrzzl** [comment]
Please look into https://github.com/gookit/validate/issues/105, and you can use this method to convert it first: https://www.goravel.dev/the-basics/validation.html#preparing-input-for-validation

**Comment by zKoz210** [comment]
@hwbrzzl we finally figured out the bugs of the validation package, can you update it to 1.5.1 in the future?

https://github.com/gookit/validate/releases/tag/v1.5.1

**Comment by hwbrzzl** [comment]
Yes, we will upgrade it to 1.5.* in 1.13.0 of Goravel.
