### ISSUE TITLE
🐛 [Bug] How do you use gorm INSERT IGNORE expression?

### ISSUE THREAD

**Issue by rajuaryan21** [goravel/goravel#227]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [ ] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

Linux

### Golang Version (Go 版本)

1.18.x

### Goravel Version (Goravel 版本)

1.12

### Describe The Problem (描述问题)

I see we are using the Gorm library under the hood to power our own Orm module.

so, do we have any facility to use the gorm insert ignore expression in our query?  something like: db.Clauses(clause.Insert{Modifier: "IGNORE"}).Create(&user)

### Reproduction Code (复现代码或截图)

I see we are using the Gorm library under the hood to power our own Orm module.

so, do we have any facility to use the gorm insert ignore expression in our query?  something like: db.Clauses(clause.Insert{Modifier: "IGNORE"}).Create(&user)

Gorm

**Comment by hwbrzzl** [comment]
You can try the `facades.Orm().Query().FirstOrCreate()` method.

**Comment by rajuaryan21** [comment]
I have a collection of models to insert or ignore. I don’t think it will work.

**Comment by hwbrzzl** [comment]
"a collection of models to insert or ignore"? For example?

**Comment by rajuaryan21** [comment]
yes, based on the primary key… insert ignore statement does this in gorm or in raw sql

**Comment by rajuaryan21** [comment]
INSERT IGNORE INTO table(column_list)
VALUES( value_list),
      ( value_list),
      ...

**Comment by hwbrzzl** [comment]
I think you can execute the original SQL directly for this situation: https://www.goravel.dev/ORM/getting-started.html#execute-native-update-sql

**Comment by rajuaryan21** [comment]
I did the same. But there are many other modifiers in gorm and other query facilities that makes things easy for advance query. We can simply provide a gorm db instance for user to use.

**Comment by hwbrzzl** [comment]
Yes, there are some advanced usages that we can add, could you please add a feature issue to provide what you want? We can make a discussion first, but in general, Goravel doesn't export a third package instance directly, we don't want to have a strong dependency.

**Comment by hwbrzzl** [comment]
I close this issue first, feel free reopen it if needid.
