### ISSUE TITLE
🐛 [Bug] 

### ISSUE THREAD

**Issue by rajuaryan21** [goravel/goravel#232]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [X] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

Linux

### Golang Version (Go 版本)

1.18.x

### Goravel Version (Goravel 版本)

1.12.0

### Describe The Problem (描述问题)

how to get the last inserted id in MySQL database using goravel?

### Reproduction Code (复现代码或截图)

how to get the last inserted id in MySQL database using goravel?

**Comment by rajuaryan21** [comment]
actually when we query using create like : facades.Orm().Query().Create(p) and then want to get the newly created model id

**Comment by hwbrzzl** [comment]
```
user := User{Name: "tom", Age: 18}
res := facades.Orm().Query().Create(&user)
fmt.Println(user.ID)
```

This is not a bug, you can create a new discussion next time. https://github.com/goravel/goravel/discussions
