### ISSUE TITLE
✨ [Feature] two-dimensional and multi-dimensional JSON arrays supports for Input/Json method

### ISSUE THREAD

**Issue by devhaozi** [goravel/goravel#233]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

Add two-dimensional and multi-dimensional JSON arrays supports for Input/Json method of Request.

**Comment by hwbrzzl** [comment]
Could you please give an example?

**Comment by DevHaoZi** [comment]
> Could you please give an example?

```
{
    "name": ["a", "b"],
    "sex": 1
}
```
Such as this.

**Comment by hwbrzzl** [comment]
You mean `ctx.Request().Input()` and `ctx.Response().Json()`?

**Comment by DevHaoZi** [comment]
> You mean `ctx.Request().Input()` and `ctx.Response().Json()`?

Yes, currently we can only get it by binding to a struct.

**Comment by DevHaoZi** [comment]
> > You mean `ctx.Request().Input()` and `ctx.Response().Json()`?
> 
> Yes, currently we can only get it by binding to a struct.

Maybe we can adding JsonArray, JsonMap, InputArray, InputMap methods.

**Comment by hwbrzzl** [comment]
I got `Input("location.city")`, but `ctx.Response().Json()` seems to support struct and slice:

<img width="1098" alt="image" src="https://github.com/goravel/goravel/assets/24771476/b8410e51-aefc-4b52-95d6-c906e234e24c">

**Comment by DevHaoZi** [comment]
> I got `Input("location.city")`, but `ctx.Response().Json()` seems to support struct and slice:
> 
> <img alt="image" width="1098" src="https://user-images.githubusercontent.com/24771476/259716461-b8410e51-aefc-4b52-95d6-c906e234e24c.png">

`Request()`, not `Response()`

**Comment by hwbrzzl** [comment]
Yeah, `ctx.Request().Json()` is deprecated, we will remove it.
