### ISSUE TITLE
🐛 [Bug] Some issues for goravel/fiber

### ISSUE THREAD

**Issue by hwbrzzl** [goravel/goravel#237]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [X] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

Linux

### Golang Version (Go 版本)

1.20.x

### Goravel Version (Goravel 版本)

master

### Describe The Problem (描述问题)

1. The action of `QueryArray` and `QueryMap` are not consistent with `goravel/gin`:

<img width="1920" alt="image" src="https://github.com/goravel/goravel/assets/24771476/9b3e1818-277b-4dfc-b051-8b99bb527f6c">

2. Some test cases don't assert expectBody:

<img width="1920" alt="image" src="https://github.com/goravel/goravel/assets/24771476/6da7218a-cf87-4a26-8f36-ac7dcae0db7c">

### Reproduction Code (复现代码或截图)

As shown above

**Comment by devhaozi** [comment]
expectBody不好实现，因为`sonic`返回的`json`数据，不会进行字典序排序，所以每次请求所返回的数据前后顺序会有所区别，就去掉了。

**Comment by devhaozi** [comment]
> expectBody不好实现，因为`sonic`返回的`json`数据，不会进行字典序排序，所以每次请求所返回的数据前后顺序会有所区别，就去掉了。

也许可以通过把二者都`Unmarshal`回去，然后再比较`map`是否相等来实现，晚上处理一下，顺便同步`gin`的更改过来。

**Comment by hwbrzzl** [comment]
也可以使用 `strings.Contain` 多判断几个关键字，把 `expectBody` 的判断改为 `assert func()` （每个 case 独立写自己的 assert）的判断。另外 gin 目前的判断应该是对的？

**Comment by devhaozi** [comment]
> 也可以使用 `strings.Contain` 多判断几个关键字，把 `expectBody` 的判断改为 `assert func()` （每个 case 独立写自己的 assert）的判断。另外 gin 目前的判断应该是对的？

`gin`没有问题，`gin`使用`sonic`需要自行指定编译`tag`，默认还是用的`encoding/json`。
