### ISSUE TITLE
✨ [Feature] 希望能实现多守卫多配置文件或者共用配置文件但多个配置的功能

### ISSUE THREAD

**Issue by liushuai05** [goravel/goravel#238]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

希望能实现多守卫分开多个配置
场景：
客户要求小程序登录要尽量保持更久的时间，最好在1个月左右再提醒重新登录，否则弹出登录次数太频繁对客户体验不是很好
但是后台相对来说登录过期时间又不能太久，否则会有安全风险。

**Comment by okami-chen** [comment]
手动生成token呗
