### ISSUE TITLE
facades.Validation.AddRules 多个验证规则后，进行校验，最后只能执行后来加入的那个规则

### ISSUE THREAD

**Issue by 1977798228** [goravel/goravel#24]
我前后添加了自定义规则，验证执行后添加的
![image](https://user-images.githubusercontent.com/23191703/210189847-8fcc9543-0fd9-4474-bdb5-d936b8c5942b.png)

我把添加的顺序换一下，验证依然是执行后添加的
![image](https://user-images.githubusercontent.com/23191703/210189913-e5d5e1f1-3658-4db8-beba-53047d0985d3.png)

**Comment by hwbrzzl** [comment]
感谢 Issue，已修复，发布了 v1.7.2。可以试下，如果还有问题请留言，或者可以关闭该 Issue。
