### ISSUE TITLE
✨ [Feature] Optimize the return of controller

### ISSUE THREAD

**Issue by hwbrzzl** [goravel/goravel#243]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

Current:

```
func (r *UserController) Show(ctx http.Context) {
	ctx.Response().Success().Json(http.Json{
		"Hello": "Goravel",
	})

        return
}
```

Optimized:

```
func (r *UserController) Show(ctx http.Context) http.Response {
	return ctx.Response().Success().Json(http.Json{
		"Hello": "Goravel",
	})
}
```

After optimizing, User can return a response directly instead of adding a new line for return.

**Comment by hwbrzzl** [comment]
Hi @devhaozi @kkumar-gcc What do you think about this please?

**Comment by devhaozi** [comment]
> Hi @devhaozi @kkumar-gcc What do you think about this please?

Looks good.

**Comment by kkumar-gcc** [comment]
> Hi @devhaozi @kkumar-gcc What do you think about this please?

Yeah, I think we should add this.

**Comment by hwbrzzl** [comment]
Let me do it.
