### ISSUE TITLE
✨ [Feature] The trace printed by facades.Log().Error uses reverse order

### ISSUE THREAD

**Issue by hwbrzzl** [goravel/goravel#244]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

<img width="785" alt="image" src="https://github.com/goravel/goravel/assets/24771476/93e8928f-9c14-473a-b6a3-001e11b03c43">

**Comment by kkumar-gcc** [comment]
@hwbrzzl  This is the expected behavior. [Eris](https://github.com/rotisserie/eris) will print errors in reverse order by default. If you want to add them in a different order, we can also do that.
![image](https://github.com/goravel/goravel/assets/84431594/f17a1b13-e158-4864-bf8f-c0038a0642df)
