### ISSUE TITLE
🐛 [Bug] Query().Save(&user) Panics when ID is uuid or string

### ISSUE THREAD

**Issue by oseintow** [goravel/goravel#246]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [ ] The problem can be stably reproduced (这个问题可以被稳定复现)
- [ ] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

MacOS

### Golang Version (Go 版本)

1.20.x

### Goravel Version (Goravel 版本)

1.12.6

### Describe The Problem (描述问题)

Database: Postgresql

I'm using field uuid with type uuid as the primary key. I am able to create a new record  but unable to update/save.
It panics when I try to save using `err := facades.Orm().Query().Save(&u)`

error: ` http: panic serving 127.0.0.1:63627: reflect: NumField of non-struct type *models.User
goroutine 15 [running]:`

### Reproduction Code (复现代码或截图)

```go
type User struct {
	//orm.Model `json:"-"`
	UUID           uuid.UUID       `gorm:"type:uuid;column:uuid;primaryKey;default:uuid_generate_v4()" json:"id" json:"id,omitempty"`
	FirstName      string          `json:"first_name"`
	LastName       string          `json:"last_name"`
	Email          string          `json:"email" json:"email,omitempty"`
	DeletedAt      gorm.DeletedAt  `gorm:"column:deleted_at" json:"-"`
	CreatedAt      carbon.DateTime `gorm:"autoCreateTime;column:created_at" json:"created_at"`
}


func (u *User) UpdateMe(data map[string]any) error {
	if firstName, ok := data["first_name"]; ok {
		u.FirstName = firstName.(string)
	}

	if lastName, ok := data["last_name"]; ok {
		u.LastName = lastName.(string)
	}

	err := facades.Orm().Query().Save(&u)
	//
	if err != nil {
		return err
	}

	return nil
}
```

**Comment by hwbrzzl** [comment]
Change to：
```
err := facades.Orm().Query().Save(u)
```
