### ISSUE TITLE
🐛 [Bug] Digital Ocean App Server Cannot Find .env

### ISSUE THREAD

**Issue by jjjrmy** [goravel/goravel#258]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [ ] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

Linux

### Golang Version (Go 版本)

1.20.x

### Goravel Version (Goravel 版本)

1.13

### Describe The Problem (描述问题)

When creating a Digital Ocean App on their App Platform, Goravel is unable to find the environment.
Because of this the application is unable to finish deploying.

### Reproduction Code (复现代码或截图)

```
[2023-09-20 03:35:47] Please create .env and initialize it first.
[2023-09-20 03:35:47] Example command: 
[2023-09-20 03:35:47] cp .env.example .env && go run . artisan key:generate
```

**Comment by hwbrzzl** [comment]
You need to add these files with your compiled application to the server:

<img width="646" alt="image" src="https://github.com/goravel/goravel/assets/24771476/3970d2d6-f1be-4f6d-a78e-876da5c1f446">

**Comment by jjjrmy** [comment]
but there isn't an actual `.env` file because the Environment configs are handled by the Digital Ocean panel.

**Comment by hwbrzzl** [comment]
For this situation, you need to implement your own route_service_provider.go and cover the system‘s.

<img width="679" alt="image" src="https://github.com/goravel/goravel/assets/24771476/4f6b2e25-5c08-44ca-b18c-fa849b22a950">

<img width="821" alt="image" src="https://github.com/goravel/goravel/assets/24771476/36e6fdb8-d0a2-471e-bab1-f2846092d2b5">

```
app.Singleton(Binding, func(app foundation.Application) (any, error) {
    return {{Your own instance}}, nil
})
```

**Comment by jjjrmy** [comment]
I'm new to GoLang. Is there an existing package to support this?

**Comment by hwbrzzl** [comment]
No, I think to add a .env file is the easy way for you.

**Comment by jjjrmy** [comment]
It’s not possible without including it in Git. And then you cannot use the
dynamic services.

**Comment by hwbrzzl** [comment]
Which service of Digital Ocean are you using?

**Comment by jjjrmy** [comment]
Digital Ocean App Platform is what it’s call

**Comment by hwbrzzl** [comment]
Okay, I'll have a try, can you simply describe your deployment process?

**Comment by jjjrmy** [comment]
Simply make an App Server from your repo and it will detect the environment
and setup the build accordingly. I did it without the Dockerfile.

**Comment by jjjrmy** [comment]
I appreciate you helping me, here is a bit more step-by-step guide.
1) https://cloud.digitalocean.com/apps/new
2) Select your Git repository and branch
3) You can click Edit Plan and select their Basic $5 monthly plan
4) Just click next through the rest of the steps and it should start deploying.

**Comment by hwbrzzl** [comment]
Related to https://github.com/goravel/goravel/issues/265, close this one.
