### ISSUE TITLE
✨ [Feature] Validation supports filter tag

### ISSUE THREAD

**Issue by hwbrzzl** [goravel/goravel#259]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

The feature: https://github.com/gookit/validate/blob/master/README.md#built-in-filters

**Comment by zh7314** [comment]
希望可以支持一些自定义的方法，不是只支持 https://github.com/gookit/validate/blob/master/README.md#built-in-filters里面的方法 like `filter:myFilter`

**Comment by hwbrzzl** [comment]
Yes, will do.

**Comment by hwbrzzl** [comment]
Duplicated: https://github.com/goravel/goravel/issues/304
