### ISSUE TITLE
✨ [Feature] Remove framework GPL dependencies

### ISSUE THREAD

**Issue by devhaozi** [goravel/goravel#261]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

According to the dependency analysis results provided by FOSSA, we may need to remove the GPL part of the framework, which is mainly used in docker testing and sqlite driver.

![image](https://github.com/goravel/goravel/assets/115467771/4bf6bd25-2434-4094-b0f4-f65467d74189)

**Comment by hwbrzzl** [comment]
Remove these packages below:
1. github.com/golang-migrate/migrate
2. github.com/glebarez/go-sqlite

**Comment by devhaozi** [comment]
We can study the implementation of https://github.com/go-gorm/playground. They did not import the docker package for testing.

**Comment by hwbrzzl** [comment]
I think if we remove the Docker testing, we will lack confidence in whether the function of Orm is normal ~ Or we can find another way to confirm this, go-gorm/playground requires active feedback from User, which is a bit passive ~

**Comment by devhaozi** [comment]
> I think if we remove the Docker testing, we will lack confidence in whether the function of Orm is normal ~ Or we can find another way to confirm this, go-gorm/playground requires active feedback from User, which is a bit passive ~

`go-gorm/playground` also use CI to run, I think it can also be done to run tests.

**Comment by hwbrzzl** [comment]
Oh, you mean this: https://github.com/go-gorm/playground/blob/master/.github/workflows/tests.yml, yes, we can check it.

**Comment by devhaozi** [comment]
> Oh, you mean this: https://github.com/go-gorm/playground/blob/master/.github/workflows/tests.yml, yes, we can check it.

Yes, they run a fully functional GORM including a variety of different databases, interesting.

**Comment by hwbrzzl** [comment]
We need to add an explanation to show how to run github/action locally.

**Comment by devhaozi** [comment]
> We need to add an explanation to show how to run github/action locally.

Running GitHub Action locally? It seems difficult. I wonder if GitHub provides a private deployment solution for Action.

**Comment by hwbrzzl** [comment]
This: https://github.com/nektos/act
