### ISSUE TITLE
✨ [Feature] The Config module supports get system environment variables

### ISSUE THREAD

**Issue by hwbrzzl** [goravel/goravel#265]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

We can set APP_KEY by `APP_KEY=123 go run .` instead of setting it in the `.env` file. The configuration variables read order is `system environment > .env > config files`.

**Comment by Maximo-Miranda** [comment]
Hi @hwbrzzl I am Maximo Miranda from (telegram), I would like to work on this function, but I have a question about "reading order", when the framework is starting this could need for example APP_PORT var, in this case first find the value in the configuration files ("with this name?"), If not exist find in the .env file and if not exist find in the system environment, if finally not found in any environment return error?, the last one is for required vars, if the var is not required do not return error!

**Comment by devhaozi** [comment]
> Hi @hwbrzzl I am Maximo Miranda from (telegram), I would like to work on this function, but I have a question about "reading order", when the framework is starting this could need for example APP_PORT var, in this case first find the value in the configuration files ("with this name?"), If not exist find in the .env file and if not exist find in the system environment, if finally not found in any environment return error?, the last one is for required vars, if the var is not required do not return error!

You think it's complicated. We use `viper` to read the configuration, so we only need to configure viper to read environment variables first.

**Comment by hwbrzzl** [comment]
Yes, you're right.

**Comment by jjjrmy** [comment]
any update on this?

**Comment by hwbrzzl** [comment]
No, not yet ~
