### ISSUE TITLE
🐛 [Bug] Remove the warning when starting

### ISSUE THREAD

**Issue by hwbrzzl** [goravel/goravel#267]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [ ] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

Linux

### Golang Version (Go 版本)

1.18.x

### Goravel Version (Goravel 版本)

1.13.x

### Describe The Problem (描述问题)

```
WARNING: sonic onlu supportsGo116~1.20 88 CPU amd64, but your environment is not suitable
```

### Reproduction Code (复现代码或截图)

```go
// Your code here
```

**Comment by hwbrzzl** [comment]
We don't seem to be able to remove this warning information. What do you think about this, please? @devhaozi

**Comment by devhaozi** [comment]
> We don't seem to be able to remove this warning information. What do you think about this, please? @devhaozi

Yes, sonic doese support arm, it will fallback to      encoding/json.

**Comment by hwbrzzl** [comment]
Yes, we want to remove the warning print, but it doesn't seem to support it.

**Comment by devhaozi** [comment]
> Yes, we want to remove the warning print, but it doesn't seem to support it.

How about submit an issue to sonic to request add a switch?

**Comment by hwbrzzl** [comment]
Here: https://github.com/bytedance/sonic/issues/535

**Comment by hwbrzzl** [comment]
@devhaozi sonic has no plan to remove this warning, how about we remove the package dependence?

**Comment by devhaozi** [comment]
> @devhaozi sonic has no plan to remove this warning, how about we remove the package dependence?

Consider add a judgement, not use it for arm.
There should be very few people using arm in the production environment.

**Comment by hwbrzzl** [comment]
Yes, we can add a helper method to add the judgment by ourselves.

**Comment by devhaozi** [comment]
> Yes, we can add a helper method to add the judgment by ourselves.

I will work for it.
