### ISSUE TITLE
🐛 [Bug] selected database is ignored when empty password provided for postgresql

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [goravel/goravel#270]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [ ] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

Linux

### Golang Version (Go 版本)

1.18.x

### Goravel Version (Goravel 版本)

1.13.0

### Describe The Problem (描述问题)

With the following env:
```env
DB_CONNECTION=postgresql
DB_HOST=127.0.0.1
DB_PORT=5432
DB_DATABASE=test
DB_USERNAME=test
DB_PASSWORD=
```
Running `go run . artisan migrate` runs migration in the default `postgres` database instead of `test` database. It looks like the problem is that the generated [dsn](https://github.com/goravel/framework/blob/431933a52640906063b435cca64fab2b39b12a07/database/db/dsn.go#L42-L53) has empty `password=` field which somehow causes the `dbname` that comes after it to be ignored: `host=127.0.0.1 user=test password= dbname=test port=5432 sslmode=disable TimeZone=UTC`

When `DB_PASSWORD` is set the migrations are run in the correct db.

I also wonder why other dsn providers generate a url but not postgres one? Wouldn't generating something like `postgres://test@localhost:5432/test?sslmode=disable` would work?

### Reproduction Code (复现代码或截图)

```go
/// Empty
```

**Comment by hwbrzzl** [comment]
Thanks for your issue, I'll test it.
