### ISSUE TITLE
✨ [Feature] Add a config to allow turning off warnings that view folder don't exist

### ISSUE THREAD

**Issue by devhaozi** [goravel/goravel#273]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

After updating the framework to version 1.13, if the `resources/views` directory does not exist, a warning message will be output every time the app is started.

I hope to add a switch to turn it off. (When working as a pure backend, there is no need to use views)

**Comment by hwbrzzl** [comment]
I think we can ignore the warning directly instead of adding a configuration.

**Comment by devhaozi** [comment]
Gin driver also need to do this, reopen it.
