### ISSUE TITLE
✨ [Feature] Add a new NoContent() method for Response

### ISSUE THREAD

**Issue by hwbrzzl** [goravel/goravel#275]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

Based on this discussion: https://github.com/goravel/goravel/discussions/274#discussioncomment-7190223

**Comment by dropout-ventures** [comment]
This is from actual Laravel if it gives you any ideas:
```php
public function noContent($status = 204, array $headers = [])
{
    return $this->make('', $status, $headers);
}
```
