### ISSUE TITLE
🐛 [Bug] Queue always print DEBUG messages with redis driver

### ISSUE THREAD

**Issue by devhaozi** [goravel/goravel#278]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [ ] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

Linux

### Golang Version (Go 版本)

1.21.x

### Goravel Version (Goravel 版本)

1.13.2

### Describe The Problem (描述问题)

Queue module always print DEBUG message when use redis driver even `APP_DEBUG` is setting to false.

### Reproduction Code (复现代码或截图)

![c20e8bc285cca7ba9f1fc0f5c928b04](https://github.com/goravel/goravel/assets/115467771/5b82e247-3348-4206-bb44-8b101bd5cd27)

**Comment by devhaozi** [comment]
link to #153

**Comment by hwbrzzl** [comment]
Fixed: https://github.com/goravel/framework/pull/459
