### ISSUE TITLE
unable to test routes when using fiber driver over gin go 

### ISSUE THREAD

**Issue by frank505** [goravel/goravel#283]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

there seems to be no way to test api calls with fiber for routing right now(i may be wrong though), i can see only the `ServeHTTP(rr, req)` method exposed which works fine with gin go and not fiber for featured tests...would be a nice addition since fiber is now supported on the framework.

**Comment by hwbrzzl** [comment]
`ServeHTTP` will be deprecated recently, you can run a goroutine and use net/http to test an API.

**Comment by frank505** [comment]
yeah thats much @hwbrzzl  better using goroutine and spinning up a channel for the test server and another to test the code against the test server, which would work perfectly fine, also not limited to fiber or gin go. thanks man :)
