### ISSUE TITLE
Can we add regex to Validate function 

### ISSUE THREAD

**Issue by frank505** [goravel/goravel#284]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

adding regular expressions so that things like password validation for example this regex regex:/^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d).+$/ ensures string has at least one capital letter, small letter and number and it can be used sort of the same way with the Validate function ```
validator, err := ctx.Request().Validate(map[string]string{
		"hash_url": "required|string",
		"password": "required|string|min:8|regex:/^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d).+$/",
	})
	if err != nil {
		return ctx.Response().Status(400).Json(
			http.Json{
				"errors": err.Error(),
			})
	}
```

**Comment by hwbrzzl** [comment]
Yes, you can do this: `required|regex:\d{4,6}`, the framework doesn't list it because there is no test case for it, we'll add it. Or you can create a custom validation,
