### ISSUE TITLE
🐛 [Bug] 中间件在未调用 `ctx.Request().Next()` 时未退出

### ISSUE THREAD

**Issue by devhaozi** [goravel/goravel#288]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [ ] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

Linux

### Golang Version (Go 版本)

1.21.x

### Goravel Version (Goravel 版本)

1.13.1

### Describe The Problem (描述问题)

预期情况应该是调用`Next()`方法，才继续向下执行，目前测试发现无论调不调用`Next()`，中间件都会直接无视它继续执行下去。

### Reproduction Code (复现代码或截图)

这样是无效的：

```go
func Static() http.Middleware {
	return func(ctx http.Context) {
		// 自动纠正 URL 格式
		if ctx.Request().Path() == services.NewSettingImpl().Get("entrance", "/") && ctx.Request().Path() != "/" {
			ctx.Response().Redirect(http.StatusFound, ctx.Request().Path()+"/")
			return
		}

		static.Serve(services.NewSettingImpl().Get("entrance", "/"), static.LocalFile("public", false))(ctx.(*gin.Context).Instance())
		ctx.Request().Next()
	}
}
```

暂时可以这样生效：

```go
func Static() http.Middleware {
	return func(ctx http.Context) {
		// 自动纠正 URL 格式
		if ctx.Request().Path() == services.NewSettingImpl().Get("entrance", "/") && ctx.Request().Path() != "/" {
			// ctx.Response().Redirect(http.StatusFound, ctx.Request().Path()+"/")
			ctx.Response().Writer().WriteHeader(http.StatusFound)
			_, err := ctx.Response().Writer().Write([]byte(fmt.Sprintf(`<html><head><meta http-equiv="refresh" content="0;url=%s/"></head></html>`, ctx.Request().Path())))
			if err != nil {
				return
			}
			ctx.Response().Flush()
			return
		}

		static.Serve(services.NewSettingImpl().Get("entrance", "/"), static.LocalFile("public", false))(ctx.(*gin.Context).Instance())
		ctx.Request().Next()
	}
}
```

**Comment by hwbrzzl** [comment]
写成这样应该就可以了 `ctx.Response().Redirect(http.StatusFound, ctx.Request().Path()+"/").Render()`，需要调用 `Render` 执行真正的跳转。

我查了下 gin 的 `Next` 逻辑，他只是区分执行中间件前与后，并没有阻止中间件执行的作用，如果要中止，需要用 `AbortWithStatus` 方法。目前我们估计不好改 `Next` 的逻辑。

**Comment by devhaozi** [comment]
> > 写成这样应该就可以了 `ctx.Response().Redirect(http.StatusFound, ctx.Request().Path()+"/").Render()`，需要调用 `Render` 执行真正的跳转。
> > 我查了下 gin 的 `Next` 逻辑，他只是区分执行中间件前与后，并没有阻止中间件执行的作用，如果要中止，需要用 `AbortWithStatus` 方法。目前我们估计不好改 `Next` 的逻辑。
> 
> 这样的话，gin 和 fiber 行为不一致，我们需要更新文档说明这一点。

还有一点是有关 contentType 的，fiber 是传入拓展名，gin 是传入完整的 mime 类型，也不一致需要说明。

fiber:

```go
ctx.Response().Data(http.StatusOK, "png", imageData)
```
gin:

```go
ctx.Response().Data(http.StatusOK, "image/png", imageData)
```

**Comment by hwbrzzl** [comment]
估计还会有其他不一致吧 ~ 文档中如果列出这些不一致，估计以后就不好维护了，可能更好的办法是让他们一致，或者我们推荐使用 Gin，如果用户使用 fiber，需要自己了解 fiber 的这些规则，例如需要传入 `png`，而不是 `image/png`。

**Comment by devhaozi** [comment]
> 估计还会有其他不一致吧 ~ 文档中如果列出这些不一致，估计以后就不好维护了，可能更好的办法是让他们一致，或者我们推荐使用 Gin，如果用户使用 fiber，需要自己了解 fiber 的这些规则，例如需要传入 `png`，而不是 `image/png`。

目前发现的不一致就这两处，第二好解决，我将开一个新 issue 让 fiber 顺从 gin 的形式，第一就比较难了~
