### ISSUE TITLE
🐛 [Bug] 调查 `gorm.io/driver/postgres` 更新导致的测试失败

### ISSUE THREAD

**Issue by devhaozi** [goravel/goravel#289]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [ ] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

Linux

### Golang Version (Go 版本)

1.21.x

### Goravel Version (Goravel 版本)

master

### Describe The Problem (描述问题)

`gorm.io/driver/postgres` 1.5.3 版本导致一项测试失败，目前已临时配置忽略这个包的更新检查。

### Reproduction Code (复现代码或截图)

![275916420-ad127943-1fab-419d-b8f4-38ea88608f4e](https://github.com/goravel/goravel/assets/115467771/7510d838-3dc1-453a-a2e3-6ed0771e0fe4)

**Comment by hwbrzzl** [comment]
Yes, gorm doesn't upgrade it again, we need to investigate by ourselves.
