### ISSUE TITLE
✨ [Feature] 我可以开发一个rabbitmq 的组件

### ISSUE THREAD

**Issue by chunyao** [goravel/goravel#306]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

我可以开发一个 rabbitmq的消息 组件

**Comment by okami-chen** [comment]
等待PR

**Comment by hwbrzzl** [comment]
欢迎开发拓展包：https://www.goravel.dev/zh/digging-deeper/package-development.html 👍
