### ISSUE TITLE
✨ [Feature] Remove github.com/glebarez/go-sqlite

### ISSUE THREAD

**Issue by hwbrzzl** [goravel/goravel#307]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

It's related to GPL-2.0-only, we need to remove it.

**Comment by hwbrzzl** [comment]
Hi @devhaozi We added this package to solve this issue: https://github.com/goravel/goravel/issues/159, now we want to remove it, what do you think about this, please?

**Comment by devhaozi** [comment]
> Hi @devhaozi We added this package to solve this issue: #159, now we want to remove it, what do you think about this, please?

I check their LICENSE: https://github.com/glebarez/go-sqlite/blob/master/LICENSE and https://gitlab.com/cznic/libc/-/blob/master/LICENSE?ref_type=heads

```
版权所有 (c) 2017 Libc作者。保留所有权利。

在不对源代码和二进制形式的软件进行或不进行修改的情况下，只要满足以下条件，就允许重新分配和使用：

    重新分发源代码必须保留上述版权声明、此条件列表和以下免责声明。
    以二进制形式重新分发必须在随分发提供的文档和/或其他材料中复制上述版权声明、此条件列表和以下免责声明。
    未经特定的事先书面许可，不得使用作者或贡献者的名字来背书或推广从本软件衍生的产品。

本软件由版权持有者和贡献者“按现状”提供，不附带任何明示或暗示的保证。包括但不限于对适销性和特定用途适用性的暗示保证。在任何情况下，版权所有者或贡献者均不对任何直接、间接、偶然、特殊、典型或后果性损害（包括但不限于采购替代商品或服务；使用、数据或利润损失；或业务中断）负责，无论这些损害是如何引起的，也无论是基于合同、严格责任还是侵权（包括疏忽或其他原因）引起的，即使已被告知可能造成此类损害的可能性。
```

```
版权所有 (c) 2017 Sqlite作者。保留所有权利。

在不对源代码和二进制形式的软件进行或不进行修改的情况下，只要满足以下条件，就允许重新分配和使用：

    重新分发源代码必须保留上述版权声明、此条件列表和以下免责声明。

    以二进制形式重新分发必须在随分发提供的文档和/或其他材料中复制上述版权声明、此条件列表和以下免责声明。

    未经特定的事先书面许可，不得使用版权持有者或其贡献者的名字来背书或推广从本软件衍生的产品。

本软件由版权持有者和贡献者“按现状”提供，不附带任何明示或暗示的保证。包括但不限于对适销性和特定用途适用性的暗示保证。在任何情况下，版权持有者或贡献者均不对任何直接、间接、偶然、特殊、典型或后果性损害（包括但不限于采购替代商品或服务；使用、数据或利润损失；或业务中断）负责，无论这些损害是如何引起的，也无论是基于合同、严格责任还是侵权（包括疏忽或其他原因）引起的，即使已被告知可能造成此类损害的可能性。
```

Seems if we add their LICENSE, we can use it in our software.

**Comment by hwbrzzl** [comment]
I think the FOSSA warning means that FOSSA finds `GPL-2.0-only` in `glebarez/go-sqlite` related packages, not `glebarez/go-sqlite` directly. So, if you check the LICENSE of `glebarez/go-sqlite`, you can't find the limit content.

**Comment by devhaozi** [comment]
> I think the FOSSA warning means that FOSSA finds `GPL-2.0-only` in `glebarez/go-sqlite` related packages, not `glebarez/go-sqlite` directly. So, if you check the LICENSE of `glebarez/go-sqlite`, you can't find the limit content.

Yes, In [https://gitlab.com/cznic/libc](https://gitlab.com/cznic/libc/-/blob/master/LICENSE?ref_type=heads), Seems no problem.

Or we can submit a issue to ask for it?
