### ISSUE TITLE
✨ [Feature]  Address handling

### ISSUE THREAD

**Issue by gedw99** [goravel/goravel#309]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

I saw that we use Carbon for Date time aspects here https://www.goravel.dev/digging-deeper/helpers.html

The other thing I would like to have is address management, which is really common.

Type of things devs need for address:

- in a gui or api you need a standard way to show and edit addresses
- Google format  sems to be the common way.

https://github.com/Boostport/address looks ok.

**Comment by hwbrzzl** [comment]
Hi @gedw99 Thanks for your suggestion, but I think we can use this package directly, instead of integrating it into Goravel, it's not like Carbon, we need to use Carbon in framework, but Address isn't required.

**Comment by gedw99** [comment]
Ok will close .

i feel like address handling is needed for s ton of use cases but ok. As KYC becomes more prevalent I needed it in 90% of apps I built lately
