### ISSUE TITLE
✨ [Feature] Prefix. route api

### ISSUE THREAD

**Issue by rymesaint** [goravel/goravel#310]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

I think it will be good if the route of api is having prefix "/api"

**Comment by hwbrzzl** [comment]
Do you mean here?

<img width="661" alt="image" src="https://github.com/goravel/goravel/assets/24771476/11d43874-9162-4a20-9652-3a4f198d6243">

**Comment by rymesaint** [comment]
i mean at routes.Api() here
![image](https://github.com/goravel/goravel/assets/4441045/464fc914-716b-4d6d-836b-b5291c9d4935)

**Comment by hwbrzzl** [comment]
Okay, thanks, I got your meaning, but we need to add the `api` prefix in `route/api.go` for now.

**Comment by Kamandlou** [comment]
We can create a group of routes with `api` prefix and then pass the router as an input to the method `routes.Api()`.
Something like this:
`route_service_provider.go`:
```
facades.Route().Prefix("api").Group(func(router route.Router) {
    routes.Api(router)
})
```

`route/api.go`:

```
func Api(router) {
	userController := controllers.NewUserController()
	router.Get("/users/{id}", userController.Show)
}
```
