### ISSUE TITLE
✨ [Feature] The lang json file supports nested folder and key.

### ISSUE THREAD

**Issue by hwbrzzl** [goravel/goravel#319]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

Folder: `/lang/en/auth.json`
Key: 
```
{
  "warning": {
    "a": "1",
    "b": "2"
  }
}
```
Get: `facades.Lang(ctx).Get("auth.warning.a") == 1`

**Comment by hwbrzzl** [comment]
FYI @kkumar-gcc

**Comment by kkumar-gcc** [comment]
> FYI @kkumar-gcc 

Do we support folder nesting?

**Comment by hwbrzzl** [comment]
Yes, I think we can support this type.

**Comment by kkumar-gcc** [comment]
> Yes, I think we can support this type.

won't it be quite challenging which is folder and which is key?
will we also support array in json file or just object?

**Comment by hwbrzzl** [comment]
> Won't it be quite challenging to determine which is the folder and which is the key?

We may be able to make a correct judgment.

> Will we also support arrays in the JSON file, or just objects?

I think only objects.
