### ISSUE TITLE
🐛 [Bug] Artisan make:package command `--root` parameter not working

### ISSUE THREAD

**Issue by devhaozi** [goravel/goravel#336]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [ ] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

Windows

### Golang Version (Go 版本)

1.21.x

### Goravel Version (Goravel 版本)

1.13.5

### Describe The Problem (描述问题)

Artisan make:package command `--root` parameter not working.

### Reproduction Code (复现代码或截图)

```bash
go run . artisan make:package sms --root=test
```

![image](https://github.com/goravel/goravel/assets/115467771/5e1397c7-bad1-4615-af0f-faf8401730c9)

**Comment by hwbrzzl** [comment]
Sorry, the document has a mistake, the command should be: `go run . artisan make:package --root=pkg sms`, the rule is limited by `github.com/urfave/cli/v2`.
