### ISSUE TITLE
✨ [Feature] batch uploads

### ISSUE THREAD

**Issue by fanqie** [goravel/goravel#339]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

The ability to fetch multiple files in the request context is urgently needed

**Comment by hwbrzzl** [comment]
Like the method of Gin: `MultipartForm`

**Comment by kkumar-gcc** [comment]
https://github.com/goravel/goravel/issues/229

**Comment by hwbrzzl** [comment]
Duplicate  with https://github.com/goravel/goravel/issues/376
