### ISSUE TITLE
✨ [Feature] Support for Automatic dependency Injection

### ISSUE THREAD

**Issue by rohitkeshwani07** [goravel/goravel#340]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

Any plans to support automatic dependency injection much like uber/fx using reflection?

**Comment by hwbrzzl** [comment]
We don't have a plan to support the feature for now, but I think it's easy to use it in the framework directly.

**Comment by devhaozi** [comment]
Close, please reopen if necessary.
