### ISSUE TITLE
✨ [Feature] Added new method orm

### ISSUE THREAD

**Issue by rymesaint** [goravel/goravel#342]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

I'm using goravel as my project right now and having more method like laravel orm such as WhereHas, WhereDoesntHave and etc. The development will be faster than now

**Comment by sCuz12** [comment]
https://github.com/goravel/framework/pull/406

**Comment by Kamandlou** [comment]
List of new methods that I added to the Goravel's ORM:

https://github.com/goravel/framework/pull/396
https://github.com/goravel/framework/pull/397
https://github.com/goravel/framework/pull/399
https://github.com/goravel/framework/pull/400
https://github.com/goravel/framework/pull/402
https://github.com/goravel/framework/pull/404
https://github.com/goravel/framework/pull/405
https://github.com/goravel/framework/pull/408
https://github.com/goravel/framework/pull/414
https://github.com/goravel/framework/pull/416
https://github.com/goravel/framework/pull/417
https://github.com/goravel/framework/pull/421

**Comment by hwbrzzl** [comment]
Move to https://github.com/goravel/goravel/issues/373
