### ISSUE TITLE
✨ [Feature] Support for Go-Prisma-Client 

### ISSUE THREAD

**Issue by hosseinmirzapur** [goravel/goravel#344]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

I'm developing a new DB tool for the Goravel project, which i'm leveraging a package named `prisma-go-client` for it. It's both "ORM" and "Migration Tool" so it can run beside the main ORM which is available on facades.Orm(). This package includes a prisma.schema for database schema and handles the migration creation and multiple database drivers supported by Prisma itself. It is fully developed in Go so there's no need to use JS for the prisma client. I wanted to see if i'm permitted to add this support to Goravel, by creating all the needed files and test files for it. Thanks in advance

**Comment by hwbrzzl** [comment]
Hi @hosseinmirzapur, thanks for your idea. The ORM module is a bit complex, and I'm not sure if `prisma-go-client` can support it totally. Please check [the document](https://www.goravel.dev/ORM/getting-started.html) carefully first. If you think it's ok, you can create a new development package to handle it.

**Comment by hosseinmirzapur** [comment]
Great, i'll let you know if i ran into any problem.

**Comment by hosseinmirzapur** [comment]
hello again have you checked my repository at [here](https://github.com/hosseinmirzapur/prisma). because i checked and it wasn't added as a standalone package/repo, i reformatted it so you can fork it and use it, if you remember.

**Comment by hwbrzzl** [comment]
Thanks @hosseinmirzapur, we can leave this packet in your organization, we are building Goravel Market, and you can submit this packet to the market in the future.
