### ISSUE TITLE
🐛 [Bug] sonic only supports Go1.16~1.20 && CPU amd64, but your environment is not suitable

### ISSUE THREAD

**Issue by crystaldaking** [goravel/goravel#351]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [ ] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

MacOS

### Golang Version (Go 版本)

1.21.x

### Goravel Version (Goravel 版本)

1.13.7

### Describe The Problem (描述问题)

I am following the instructions which is divided in the "Installation" section 
https://www.goravel.dev/getting-started/installation.html 
My configuration is for macOS Sonoma 14.2.1 and M1 Pro.
I receive the following notification after generating
```
crystal@Pavels-MacBook-Pro goravel-test % go run . artisan key: generate 
WARNING: sonic only supports Go1.16~1.20 && CPU amd64, but your environment is not suitable
```

**Comment by devhaozi** [comment]
This question seems a bit strange because the framework only uses `sonic` on x86 architecture, see: https://github.com/goravel/framework/blob/master/support/json/json_x86.go

Is there any direct use of `sonic` in your code?

**Comment by crystaldaking** [comment]
> on x86 architecture
This is actually the reason. 
Is there nothing to replace this package within the framework of ARM processors on macOS?

**Comment by devhaozi** [comment]
> This is actually the reason.

The `//go:build amd64` condition in the file will only compile sonic on x86, so I'm wondering about this behavior, can you run the following command and reply with the results?

```
github.com/bytedance/sonic
```

> Is there nothing to replace this package within the framework of ARM processors on macOS?

`sonic` will automatically fallback to the `encoding/json` implementation when it is unavailable, so the warning message will not affect use.

**Comment by eriknyk** [comment]
However this still should be fixed and conditionally supported ARM platforms
if kind `go:build amd64` is hardcoded is this shouldn't fixed?

**Comment by eddyjj92** [comment]
Este problema se ve presente al ejecutar cualquier acción en la línea de comandos, pero no afecta para nada el desarrollo.
