### ISSUE TITLE
Views

### ISSUE THREAD

**Issue by aeq-dev** [goravel/goravel#36]
Hi, thanks for this great project, I'm a laravel developer, I'm wondering is there any tuto how to work with views same as Laravel.

**Comment by hwbrzzl** [comment]
Hi, we advocate front-end separation, there is no plan to support rendering pages for the time being. If you just want to return a simple HTML code, you can use like below:
```
ctx.Response().Data(http.StatusOK, "text/html; charset=utf-8", []byte("<b>Goravel</b>"))
```

**Comment by aeq-dev** [comment]
Thanks for reply and sorry for the delay 
Please how could I use html file parsing, something like this : 
```
t, _ := template.ParseFiles("views/layout.html", "views/home/index.html")
 err := t.Execute(w, nil)
```
Thanks

**Comment by hwbrzzl** [comment]
Maybe you can follow below:

```
buf := new(bytes.Buffer)

_, err := buf.ReadFrom(w)
if err != nil {
    return nil, err
}

b := buf.Bytes()

ctx.Response().Data(http.StatusOK, "text/html; charset=utf-8", buf)
```
