### ISSUE TITLE
✨ [Feature] String helpers(example Str::uuid() in laravel)

### ISSUE THREAD

**Issue by darakanoit** [goravel/goravel#377]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

Hi, it would be great to see these helpers https://laravel.com/api/10.x/Illuminate/Support/Str.html in goravel

**Comment by kkumar-gcc** [comment]
#82

**Comment by hwbrzzl** [comment]
Yes, duplicate, close this. Thanks.
