### ISSUE TITLE
🐛 [Bug] Model的Retrieved event不会被触发

### ISSUE THREAD

**Issue by FenShenx** [goravel/goravel#385]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [ ] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

Windows

### Golang Version (Go 版本)

1.21.x

### Goravel Version (Goravel 版本)

1.13.7

### Describe The Problem (描述问题)

Model的事件中，查询时Retrieved事件不会被触发。
go版本1.22.0 

### Reproduction Code (复现代码或截图)

1、Model
```golang
type SubscriptionPlan struct {
	orm.Model
	orm.SoftDeletes
	Name            string
	Price           float64
	SubscribeMonth  int
	SubscribeCount  int
	PriceOffPercent int
	Sort            int
	Privileges      string
	PrivilegesArr   []string `gorm:"-"`
	Status          bool
	BuyCount        int
}

func (u *SubscriptionPlan) DispatchesEvents() map[contractsorm.EventType]func(contractsorm.Event) error {
	return map[contractsorm.EventType]func(contractsorm.Event) error{
		contractsorm.EventCreating: func(event contractsorm.Event) error {
			return u.setPrivileges(event)
		},

		contractsorm.EventSaving: func(event contractsorm.Event) error {
			return u.setPrivileges(event)
		},
		contractsorm.EventRetrieved: func(event contractsorm.Event) error {
			return u.getPrivileges(event)
		},
	}
}
```
2、Query
```golang
var plans []models.SubscriptionPlan
err := facades.Orm().Query().Order("created_at desc").Find(&plans)
```

**Comment by FenShenx** [comment]
我打断点调试看了一下，查询多条数据时，触发retrieved event时，入参dest的类型为 *[]models.SubscriptionPlan ，dest.(ormcontract.DispatchesEvents) 时 exist必然为false
![Uploading bug.png…]()

**Comment by FenShenx** [comment]
我打断点调试看了一下，查询多条数据时，触发retrieved event时，入参dest的类型为 *[]models.SubscriptionPlan ，dest.(ormcontract.DispatchesEvents) 时 exist必然为false

![bug](https://github.com/goravel/goravel/assets/29164623/6895ba56-4843-4f08-b634-097c94d171e6)

**Comment by hwbrzzl** [comment]
是的，只有单模型时候才会触发 `retrieved`。
