### ISSUE TITLE
✨ [Feature] Supports configuring the json serialization/deserialization package in config/app.go

### ISSUE THREAD

**Issue by devhaozi** [goravel/goravel#392]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

The current framework uses sonic by default in supported environments to provide the best performance, but this also adds 20MB to the size of the generated binary file.

In some projects where performance is not very important, I hope to have the option to choose json serialization/deserialization package.

[This is an example of fiber](https://docs.gofiber.io/guide/faster-fiber#custom-json-encoderdecoder)

**Comment by hwbrzzl** [comment]
Yes, we may remove sonic from the framework, and provide an interface to support it, we don't need a new config file, we may add the new configuration in config/app.go
