### ISSUE TITLE
✨ [Feature] Map the Installer to the Docs 

### ISSUE THREAD

**Issue by livghit** [goravel/goravel#399]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

Hi hope you are doing well . 

Wouldn't it be great to add the installer to the docs . With it we could see what features we want to add and improve with the installer .

**Comment by hwbrzzl** [comment]
Hi @livghit I plan to add it when publishing v1.14, I'm dealing with the migration feature, and will publish v1.14 after it.

**Comment by hwbrzzl** [comment]
Hey @livghit  We created a private channel in Discord for contributors. You can click [the link](https://discord.gg/dMs73mSa) and DM me (@Bowen) to join it if you are interested.

Here you can:

1. Send PR link or review others' PRs;
2. Discuss new features before creating an issue;
3. Vote for something;
4. etc.
