### ISSUE TITLE
🐛 [Bug] 模型事件获取ID和模型事件触发bug

### ISSUE THREAD

**Issue by linshuboy** [goravel/goravel#405]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [ ] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

Windows

### Golang Version (Go 版本)

1.21.x

### Goravel Version (Goravel 版本)

1.13.9

### Describe The Problem (描述问题)

模型的事件回调中获取不到id,好像是因为模型中的ID字段对应了i_d
在模型中覆盖ID字段设置成 
`ID             uint            `gorm:"primaryKey,column:id" json:"id"` `
这种情况可以正常在事件回调中获取到id,但是每一次更新模型都会触发创建后事件 created

### Reproduction Code (复现代码或截图)

![image](https://github.com/goravel/goravel/assets/20389206/54e8fc49-1cc9-4bfb-82a6-c06da49a9c24)

**Comment by hwbrzzl** [comment]
可以提供一段可以复现的代码吗？thanks

**Comment by linshuboy** [comment]
[事件回调拿不到ID.patch](https://github.com/goravel/goravel/files/15288436/ID.patch)
[事件能拿到ID,但是更新也会触发创建后事件.patch](https://github.com/goravel/goravel/files/15288437/ID.patch)

**Comment by linshuboy** [comment]
> 可以提供一段可以复现的代码吗？如果能够更进一步在 https://github.com/goravel/example 中提供一个复现 PR 将会更好。thanks！

上面是分别复现两种情况的补丁文件,希望能帮助到你

**Comment by hwbrzzl** [comment]
事件回调拿不到ID: 是因为 `id` 被嵌套在了 `orm.Model` 中，框架上没处理到这个情况，将会修复下，目前你可以将 `orm.Model` 定义的内容整体移到外层，这样就可以拿到 `id` 了；

事件能拿到ID,但是更新也会触发创建后事件：应该是因为你定义了两个 primaryKey，可以删除下图的 ID 试下，应该就不会触发 created 了，但这时会变为第一种情况，拿不到 `id`。

<img width="625" alt="image" src="https://github.com/goravel/goravel/assets/24771476/ac8fc3c9-3d1a-45c4-8898-5641c156f780">

感谢反馈！

**Comment by linshuboy** [comment]
> 事件回调拿不到ID: 是因为 `id` 被嵌套在了 `orm.Model` 中，框架上没处理到这个情况，将会修复下，目前你可以将 `orm.Model` 定义的内容整体移到外层，这样就可以拿到 `id` 了；
> 
> 事件能拿到ID,但是更新也会触发创建后事件：应该是因为你定义了两个 primaryKey，可以删除下图的 ID 试下，应该就不会触发 created 了，但这时会变为第一种情况，拿不到 `id`。
> 
> <img alt="image" width="625" src="https://private-user-images.githubusercontent.com/24771476/330488644-ac8fc3c9-3d1a-45c4-8898-5641c156f780.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NTQ4NzIsIm5iZiI6MTcxNTc1NDU3MiwicGF0aCI6Ii8yNDc3MTQ3Ni8zMzA0ODg2NDQtYWM4ZmMzYzktM2QxYS00NWM0LTg4OTgtNTY0MWMxNTZmNzgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDA2MjkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MjkyNWE1NDgyZGQ4MThjYzY0NmM1NzMxMDQ2ZTMzMGViODY2Y2QxZWI0MGJlZGQxMGYzN2U2NWY0ZTA4NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IP4h_nXbaCDDi4UNPyOED3dsFXw7EMYRixTrpnx_nUM">
> 感谢反馈！

感谢响应,这个问题修复会在短时间之内上线吗?

**Comment by hwbrzzl** [comment]
是的，预期会修复到 1.13.10
