### ISSUE TITLE
✨ [Feature] - Any support for sqlx

### ISSUE THREAD

**Issue by sujit-baniya** [goravel/goravel#409]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

I wanted to use https://github.com/jmoiron/sqlx instead of Gorm. Is there any support for sqlx

**Comment by hwbrzzl** [comment]
Yes, we have an issue to implment this: https://github.com/goravel/goravel/issues/358
