### ISSUE TITLE
✨ [Feature] translation support set lang path

### ISSUE THREAD

**Issue by devhaozi** [goravel/goravel#414]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

The current value is hard-coded, it is recommended to modify it to the config item.

![image](https://github.com/goravel/goravel/assets/115467771/91f59210-ab36-445d-9fd9-cbe59d101496)

**Comment by hwbrzzl** [comment]
Maybe not necessary? Do you have a specific use case?

**Comment by devhaozi** [comment]
> Maybe not necessary? Do you have a specific use case?

Like this, if do not run directly in the application directory, you will not be able to read the translation file correctly

![image](https://github.com/goravel/goravel/assets/115467771/2df41643-74e4-4cf8-bc0d-0062fcfc2cd3)

**Comment by devhaozi** [comment]
> > Maybe not necessary? Do you have a specific use case?
> 
> Like this, if do not run directly in the application directory, will not be able to read the translation file correctly.
> 
> ![image](https://private-user-images.githubusercontent.com/115467771/333769457-3673a499-2f05-4d94-aba1-f1449627ca18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MDg1MDIsIm5iZiI6MTcxNjYwODIwMiwicGF0aCI6Ii8xMTU0Njc3NzEvMzMzNzY5NDU3LTM2NzNhNDk5LTJmMDUtNGQ5NC1hYmExLWYxNDQ5NjI3Y2ExOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQwMzM2NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MzhhNmZhMmMxOWYyNWM1MGYyNTI4ODIxZmM0NjFlMTVhZTMxOTNlZTE4ZjY1NDc1N2RmYzE4YTQ3YjcxZmNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pBvozMZUxIywsJ-xT5ViePcpIeIuleiwM2em6l5PL5s)

Or is there any way to locate the path where the binary file is located, and then use this as a starting point to read translation file.

**Comment by devhaozi** [comment]
I will work for this

**Comment by hwbrzzl** [comment]
Makes sense for this case, we may add a configuration in config/app.go
