### ISSUE TITLE
✨ [Feature] Default api route

### ISSUE THREAD

**Issue by jonathanch96** [goravel/goravel#415]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

I noticed that we are trying to split the web routes and API routes. However, in Laravel, when we define our routes in api.php, it automatically appends /api to the routes.

We can implement this approach in  app/providers/route_service_provider.go
![image](https://github.com/goravel/goravel/assets/30033632/867421cd-4c35-4a00-a73d-23e690866e1e)

And in web.go and api.go
![image](https://github.com/goravel/goravel/assets/30033632/4bf30811-dfe1-44b0-9bb7-ec12141227cd)

![image](https://github.com/goravel/goravel/assets/30033632/c326950b-9129-4b17-898f-7656340b57b9)

and the result will be like this
![image](https://github.com/goravel/goravel/assets/30033632/9c16b943-0601-4d45-9d8e-4831a91868f9)

**Comment by hwbrzzl** [comment]
Yes, a good implementation 👍 We don't do this default because most users only provide API through Golang, and we also don't recommend implementing FE and BE in Goravel, although Goravel supports templates. But if some users want to implement this, they can achieve it simply.
