### ISSUE TITLE
✨ [Feature] Set validator message language same as APP_LOCALE

### ISSUE THREAD

**Issue by devhaozi** [goravel/goravel#418]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

```
import "github.com/gookit/validate/locales/zhcn"

zhcn.RegisterGlobal()
```

**Comment by hwbrzzl** [comment]
Maybe can merge to https://github.com/goravel/goravel/issues/417?
