### ISSUE TITLE
🐛 [Bug] Your connection is not private when opening goravel.dev

### ISSUE THREAD

**Issue by damywise** [goravel/goravel#421]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [ ] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

MacOS

### Golang Version (Go 版本)

1.21.x

### Goravel Version (Goravel 版本)

idk sorry

### Describe The Problem (描述问题)

1. Open goravel.dev
2. <img width="711" alt="Screenshot 2024-05-30 at 15 01 18" src="https://github.com/goravel/goravel/assets/162382722/0a5d76f7-df70-472e-bfbb-f0efe1119a16">

**Comment by hwbrzzl** [comment]
Thanks for your feedback, fixed.
