### ISSUE TITLE
🐛 [Bug] Unable to run the app when using Redis as the cache driver in config/cache.go.

### ISSUE THREAD

**Issue by neosign** [goravel/goravel#425]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [X] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

Windows

### Golang Version (Go 版本)

1.21.x

### Goravel Version (Goravel 版本)

https://github.com/goravel/goravel/issues

### Describe The Problem (描述问题)

1. In this environment... 
My windows 10 machine as describe above
Redis Server was running fine on default port ,  (I checked with redis-cli and other client tool just work fine)
2. With this config...
.env

`REDIS_HOST=127.0.0.1
REDIS_PASSWORD=
REDIS_PORT=6379`

app/config/cache.go
`"stores": map[string]any{
			"memory": map[string]any{
				"driver": "memory",
			},
			"redis": map[string]any{
				"driver": "redis",
			},`
_**Maybe I am so new about the go programming  but it should be like this?**_
**_Memory Driver works fine._**
			
4. Run 'air'
5. See error...
`local.error: invalid driver: redis, only support memory, custom`
`trace:
                log.(*Writer).withStackTrace:C:******/go/pkg/mod/github.com/goravel/framework@v1.13.7/log/logrus_writer.go:195
        log.(*Writer).Error:******/go/pkg/mod/github.com/goravel/framework@v1.13.7/log/logrus_writer.go:99
        cache.(*Application).Store:******/go/pkg/mod/github.com/goravel/framework@v1.13.7/cache/application.go:42
        routes.Web:******example-master/example-master/routes/web.go:80
        providers.(*RouteServiceProvider).Boot:******example-master/example-master/app/providers/route_service_provider.go:22
        foundation.(*Application).bootServiceProviders:******/go/pkg/mod/github.com/goravel/framework@v1.13.7/foundation/application.go:163
        foundation.(*Application).bootConfiguredServiceProviders:******/go/pkg/mod/github.com/goravel/framework@v1.13.7/foundation/application.go:150
        foundation.(*Application).Boot:******/go/pkg/mod/github.com/goravel/framework@v1.13.7/foundation/application.go:49      
        bootstrap.Boot:******example-master/example-master/bootstrap/app.go:13
        main.main:******example-master/example-master/main.go:11
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x29725d6]`

### Reproduction Code (复现代码或截图)

1.modify app/config/cache.go with Redis Driver
`	"stores": map[string]any{
			"memory": map[string]any{
				"driver": "memory",
			},
			"redis": map[string]any{
				"driver": "redis",
			},
		},`
2.run command air or go run .

**Comment by hwbrzzl** [comment]
Should be `custom`

<img width="906" alt="image" src="https://github.com/goravel/goravel/assets/24771476/5f11e0b9-3f20-4ec2-b410-77dad0c430d0">

**Comment by neosign** [comment]
thanks, it works like charm now

> Should be `custom`
> 
> <img alt="image" width="906" src="https://private-user-images.githubusercontent.com/24771476/335870954-5f11e0b9-3f20-4ec2-b410-77dad0c430d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTA0ODAsIm5iZiI6MTcxNzQ5MDE4MCwicGF0aCI6Ii8yNDc3MTQ3Ni8zMzU4NzA5NTQtNWYxMWUwYjktM2YyMC00ZWMyLWI0MTAtNzdkYWQwYzQzMGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA4MzYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxZjdmMzUwYzRmMWVhODNkYmExNGI2YWE4MTI5YWM3ODVmMDE5YzVhOTRkMDRmOGEzMTFkNWE2ZjRmZGJlMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cu9QoxPVuDrQPKaE8VNezP1_VAMy3DcKPrS-GqHlj7I">
