### ISSUE TITLE
🐛 [Bug] fiber driver missing some method implement in version v1.1.14

### ISSUE THREAD

**Issue by izcream** [goravel/goravel#429]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [ ] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

Linux

### Golang Version (Go 版本)

1.21.x

### Goravel Version (Goravel 版本)

1.14.0

### Goravel fiber driver version
1.1.14

### Describe The Problem (描述问题)

just clone goravel project and add fiber http driver then run. its will return error message below
![image](https://github.com/goravel/goravel/assets/10282500/45d94268-6756-4b6c-9b78-b76d81aba002)

I see method implement is exists in repo source code. but in build package from golang look like that method is disappearing in file

workaround: copy missing method from golavel/fiber repository source to local go package in machine, then it's will work fine

**Comment by hwbrzzl** [comment]
Sorry, I forgot to release goravel/fiber v1.2.0, but have done it now, please upgrade goravel/fiber to v1.2.0.
