### ISSUE TITLE
🐛 [Bug] Session gets deleted/forgotten when loading StaticFS routes with Disable Cache

### ISSUE THREAD

**Issue by AndreiTelteu** [goravel/goravel#432]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [ ] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

Windows

### Golang Version (Go 版本)

1.22.3

### Goravel Version (Goravel 版本)

1.14.0

### Describe The Problem (描述问题)

1. In this environment... Windows WSL, but goravel with air is configured in a docker container
2. With this config...
When you click on a flag we set 'lang' in session, and then a global middleware takes that and changes the language with the new localization feature.
Because of the StaticFS route, when I check "Disable Cache" I belive those /assets/ routes are resettings the session because they don't see the session cookie.

https://github.com/goravel/goravel/assets/5564199/8f8a825e-7d5e-4b55-8919-80597de068db

The workaround solution I found:
I removed those middlewares from app/http/kernel and I applied them on every route.
```go
func Web() {
	facades.Route().StaticFS("assets", http.Dir("./public/assets"))
	homeController := controllers.NewHomeController()

	facades.Route().
		Middleware(
			sessionmiddleware.StartSession(),
			middleware.SessionLanguage(),
		).
		Group(func(router route.Router) {
			router.Get("/", homeController.Index)
			router.Get("/change-lang/{lang}", services.NewLangService().HandleChangeLang)
		})
	...
}
```
And now it works with disable cache. 

### Reproduction Code (复现代码或截图)

```go
// global middlewared in /app/http/kernel.go
func (kernel Kernel) Middleware() []http.Middleware {
	return []http.Middleware{
		sessionmiddleware.StartSession(),
		middleware.SessionLanguage(),
	}
}
// app/http/middleware/session_language.go
func SessionLanguage() http.Middleware {
	return func(ctx http.Context) {
		if ctx.Request().HasSession() && ctx.Request().Session().Exists("lang") {
			if lang, ok := ctx.Request().Session().Get("lang").(string); ok {
				facades.App().SetLocale(ctx, lang)       // does not work at this moment
				facades.Config().Add("app.locale", lang) // this works !!!
				ctx.Request().Next()
				return
			}
		}
		facades.App().SetLocale(ctx, "ro")       // does not work at this moment
		facades.Config().Add("app.locale", "ro") // this works !!!
		ctx.Request().Next()
	}
}
// when you click on a flag i just execute
lang := ctx.Request().Route("lang")
ctx.Request().Session().Put("lang", lang)
return ctx.Response().Redirect(
	http.StatusFound,
	ctx.Request().Header("Referer", "/"),
)
// the route that seems to be the issue is
facades.Route().StaticFS("assets", http.Dir("./public/assets"))
// in the assets folder i have those flags that you see on the video
```

**Comment by hwbrzzl** [comment]
Should be solved in v1.14.1, please let me know if there is still any issue.
