### ISSUE TITLE
🐛 [Bug] 

### ISSUE THREAD

**Issue by luengwaiban** [goravel/goravel#445]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [ ] The problem can be stably reproduced (这个问题可以被稳定复现)
- [ ] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

MacOS

### Golang Version (Go 版本)

1.21.x

### Goravel Version (Goravel 版本)

1.14.1

### Describe The Problem (描述问题)

每次升级需要手动修改的东西比较多，如果使用安装器的话，能都免去这些升级的改动？而是使用一个命令就可以完成升级

### Reproduction Code (复现代码或截图)

```go
// Your code here
```

**Comment by devhaozi** [comment]
做不到，框架尽量会把跨版本升级用时控制在 20 分钟以内。

**Comment by hwbrzzl** [comment]
以后有望使用脚本实现升级，目前的话会尽量控制升级的成本。
