### ISSUE TITLE
🐛 [Bug] redis 到底要怎么配置, 按照redis的文档, 还是报错

### ISSUE THREAD

**Issue by wcz0** [goravel/goravel#469]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [ ] The problem can be stably reproduced (这个问题可以被稳定复现)
- [ ] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

MacOS

### Golang Version (Go 版本)

1.21.x

### Goravel Version (Goravel 版本)

1.14.4

### Describe The Problem (描述问题)

1.cache.go
```go
package config

import (
	"github.com/goravel/framework/facades"
	"github.com/goravel/framework/contracts/cache"
    redisfacades "github.com/goravel/redis/facades"
)

func init() {
	config := facades.Config()
	config.Add("cache", map[string]any{
		// Default Cache Store
		//
		// This option controls the default cache connection that gets used while
		// using this caching library. This connection is used when another is
		// not explicitly specified when executing a given caching function.
		"default": config.Env("CACHE_STORE", "memory"),

		// Cache Stores
		//
		// Here you may define all the cache "stores" for your application as
		// well as their drivers. You may even define multiple stores for the
		// same cache driver to group types of items stored in your caches.
		// Available Drivers: "memory", "custom"
		"store": map[string]any{
			"memory": map[string]any{
				"driver": "memory",
			},
			"redis": map[string]any{
				"driver": "custom",
				"connection": "default",
				"via": func() (cache.Driver, error) {
					return redisfacades.Redis("redis"), nil // The `redis` value is the key of `stores`
				},
			},
		},

		// Cache Key Prefix
		//
		// When utilizing a RAM based store such as APC or Memcached, there might
		// be other applications utilizing the same cache. So, we'll specify a
		// value to get prefixed to all our keys, so we can avoid collisions.
		// Must: a-zA-Z0-9_-
		"prefix": config.GetString("APP_NAME", "goravel") + "_cache",
	})
}
```

.env
CACHE_STORE=redis

### Reproduction Code (复现代码或截图)

<img width="520" alt="image" src="https://github.com/user-attachments/assets/ae780498-0d64-4821-8c55-32f50a5f5752">

**Comment by hwbrzzl** [comment]
少了一个字母 `s`，请问你使用的是什么版本？

<img width="702" alt="image" src="https://github.com/user-attachments/assets/6e9a67f3-54ba-4e4e-8fe5-ed21b623cd08">

<img width="870" alt="image" src="https://github.com/user-attachments/assets/8a14ab6c-b2ea-4a42-ae6a-ce8cb123fece">

**Comment by wcz0** [comment]
漏s应该是我自己修改的问题. 
下面这个是按照配置来的. 
<img width="963" alt="image" src="https://github.com/user-attachments/assets/1edecdd3-cd00-4e7c-b630-1d4ebaa49682">

**Comment by hwbrzzl** [comment]
看这两步对不对 

<img width="1103" alt="image" src="https://github.com/user-attachments/assets/98e805cd-68b8-4cf1-aeb5-f227a543ca67">

**Comment by wcz0** [comment]
完全复制redis的文档, 新拉的一个goravel项目还是会报错

**Comment by devhaozi** [comment]
给example仓库创建一个可复现的PR我们看看。

**Comment by wcz0** [comment]
> 给example仓库创建一个可复现的PR我们看看。

https://github.com/goravel/example/pull/25

**Comment by hwbrzzl** [comment]
> 看这两步对不对
> 
> <img alt="image" width="1103" src="https://private-user-images.githubusercontent.com/24771476/356990805-98e805cd-68b8-4cf1-aeb5-f227a543ca67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MTExMDYsIm5iZiI6MTcyMzUxMDgwNiwicGF0aCI6Ii8yNDc3MTQ3Ni8zNTY5OTA4MDUtOThlODA1Y2QtNjhiOC00Y2YxLWFlYjUtZjIyN2E1NDNjYTY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDAxMDAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNDNjMmRmZTdjMjJiMmZkNGI2YmY3OTJlYzBmMmMyZDVkY2Q5ZTY3ODNmODQ0MTg0NzlkZGQ2YjQ0MWNmYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0JCtSqI3em4FaaqjWL2Lu4hliXv0UxswrsIoPOCNR7g">

在上面PR中，第2步配置的不对（注意注释内容） ，第4步没有配置。

**Comment by wcz0** [comment]
不好意思. 给你们造成的困扰. 已支持开源
