### ISSUE TITLE
✨ [Feature] Introduce a WhereHas() Method for Filtering Records with Related Entries in Another Table, Similar to Laravel

### ISSUE THREAD

**Issue by shayan-yousefi** [goravel/goravel#475]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

## Proposed Feature: `WhereHas()` Method for Filtering Records Based on Related Entries

I propose adding a `WhereHas()` method similar to Laravel's, which would allow filtering records based on the presence of related records in another table. This method would accept a relation name and conditions, including the possibility of passing a callback function for more customized queries.

### Suggested Method Signatures:
1. **`WhereHas(relation string, callback func(), operator string, count int)`**  
   *Note:* The `relation` parameter as a string would require a `Model()` method to determine the related model.

2. **`WhereHas(relation any {model}, callback func(), operator string, count int)`**

3. **`WhereHas(relation {any or string}, args ...any)`**

I'd like to hear your thoughts and suggestions on this implementation before moving forward.

**Comment by shayan-yousefi** [comment]
I want to start it. Is there any suggestion?

**Comment by hwbrzzl** [comment]
Hi @shayan-yousefi I appreciated that. There is already the same issue: https://github.com/goravel/goravel/issues/373, and there is a closed PR, you can check it first.

**Comment by hwbrzzl** [comment]
Hey @shayan-yousefi   We created a private channel in Discord for contributors. You can click [the link](https://discord.gg/dMs73mSa) and DM me (@Bowen) to join it if you are interested.

Here you can:

1. Send PR link or review others' PRs;
2. Discuss new features before creating an issue;
3. Vote for something;
4. etc.
