### ISSUE TITLE
🐛 [Bug] Events not being dispatched when saving models 

### ISSUE THREAD

**Issue by tekpriest** [goravel/goravel#476]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [x] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

MacOS

### Golang Version (Go 版本)

1.21.x

### Goravel Version (Goravel 版本)

1.0.0

### Describe The Problem (描述问题)

1. Create a model.
2. Add DispatchesEvents() method.
3. Create and save data.
4. Password does not get hashed

### Reproduction Code (复现代码或截图)

```go
package models

import (
	"fmt"

	corm "github.com/goravel/framework/contracts/database/orm"
	"github.com/goravel/framework/database/orm"
	"github.com/goravel/framework/facades"
)

type User struct {
	orm.Timestamps
	orm.SoftDeletes
	ID       string  `gorm:"primaryKey" json:"id"`
	Name     string  `json:"name"`
	Email    string  `json:"email"`
	Password string  `json:"-"`
	Username string  `json:"username"`
	Avatar   string  `json:"avatar,omitempty"`
	Posts    []*Post `json:"posts,omitempty"`
}

func (u *User) DispatchesEvents() map[corm.EventType]func(corm.Event) error {
	return map[corm.EventType]func(corm.Event) error{
		corm.EventCreating: func(e corm.Event) error {
			password, _ := facades.Hash().Make(u.Password)
			u.Password = password
			return nil
		},
		corm.EventSaving: func(e corm.Event) error {
			password, _ := facades.Hash().Make(u.Password)
			u.Password = password
			return nil
		},
	}
}

... 
UserController
...
	user := &models.User{
		ID:       uuid.NewString(),
		Name:     request.Name,
		Email:    request.Email,
		Password: request.Password,
		Username: request.Username,
	}
	if err := c.q.Create(&user); err != nil {
		return ctx.Response().Json(http.StatusInternalServerError, http.Json{"error": err.Error()})
	}
...

```

**Comment by hwbrzzl** [comment]
You should call the `SetAttribute ` method to set the new value: https://www.goravel.dev/orm/getting-started.html#parameter-in-observer

**Comment by tekpriest** [comment]
Problem is the observer I created using artisan and also registered in the app/providers/event_service_provider.go is not being called, this is the repository https://github.com/tekpriest/goravel-blog

**Comment by hwbrzzl** [comment]
`func (u *User) DispatchesEvents()` and `UserModelObserver` shouldn't be used simultaneously. You can only use `func (u *User) DispatchesEvents()` first to test your basic logic.

**Comment by tekpriest** [comment]
that was my first implementation, same thing, so I commented it out and added observer bus same thing

**Comment by hwbrzzl** [comment]
Is it normal now?

**Comment by tekpriest** [comment]
this is what I have now
```go
func (u *User) DispatchesEvents() map[corm.EventType]func(corm.Event) error {
	return map[corm.EventType]func(corm.Event) error{
		corm.EventCreating: func(e corm.Event) error {
			password, _ := facades.Hash().Make(u.Password)
			e.SetAttribute("password", password)
			return nil
		},
		corm.EventSaving: func(e corm.Event) error {
			password, _ := facades.Hash().Make(u.Password)
			e.SetAttribute("password", password)
			return nil
		},
	}
}
```

**Comment by tekpriest** [comment]
no, it doesn't work

**Comment by tekpriest** [comment]
maybe I did have a wrong setup, I generated a new project and now it works
