### ISSUE TITLE
✨ [Feature] Configure camel case columns instead of snake case GORM

### ISSUE THREAD

**Issue by dusanbre** [goravel/goravel#477]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [ ] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

MacOS

### Golang Version (Go 版本)

1.21.x

### Goravel Version (Goravel 版本)

1.14.4

### Describe The Problem (描述问题)

This is a maybe more of feature request or hidden feature that i can not find how to configure.
Problem is with many2many relation and camel cased column names.

Db structure:

restaurants:
 - id
 - name

category: 
- id
- name

restaurant_categories:
- id
- restaurantId
- categoryId

Categories        []Category            `gorm:"many2many:restaurant_categories;foreignKey:id;joinForeignKey:restaurantId;References:id;joinReferences:categoryId" json:"categories"`

Gorm allows to change foreign keys names, etc.. but when i try to change it this `restaurantId` gorm converts this into `restaurant_id` and than throws invalid column name

Also gorm allows to configure naming strategy but i can not find way to configure this throught Facades

```

db, err := gorm.Open(sqlite.Open("gorm.db"), &gorm.Config{  
NamingStrategy: schema.NamingStrategy{    
TablePrefix: "t_",   // table name prefix, table for `User` would be `t_users`    
SingularTable: true, // use singular table name, table for `User` would be `user` with this option enabled    
NoLowerCase: true, // skip the snake_casing of names    
NameReplacer: strings.NewReplacer("CID", "Cid"), // use name replacer to change struct/field name before convert it to db name  
},})
--
```

Can you help with this?

Thanks

### Reproduction Code (复现代码或截图)

```go
// Your code here
```

**Comment by dusanbre** [comment]
Any update for this problem?

**Comment by hwbrzzl** [comment]
Hey @dusanbre So sorry, missed this issue. Yes, can't configure these parameters for now, I'll test this ManyToMany case, and provide feedback to you.

**Comment by hwbrzzl** [comment]
Hey @dusanbre Sorry for the delay, I tested this case locally, and yes, the issue can be solved when setting `NoLowerCase` and `NameReplacer`, but when setting that, you have to define the column tag for every model, otherwise, the DB fileds name will match the struct fields exactly, eg: the DB field: `restaurantId` => the struct field: `RestaurantId`. I created a PR for reference: https://github.com/goravel/example/pull/26/files.

And the `NamingStrategy` is:

```
NamingStrategy: schema.NamingStrategy{
	TablePrefix:   r.config.GetString(fmt.Sprintf("database.connections.%s.prefix", r.connection)),
	SingularTable: r.config.GetBool(fmt.Sprintf("database.connections.%s.singular", r.connection)),
	NoLowerCase:   true,
	NameReplacer:  strings.NewReplacer("RestaurantId", "restaurantId", "CategoryId", "categoryId"),
},
```

Are you eager to have this feature in v1.14? Otherwise, I'll add it in v1.15.

**Comment by dusanbre** [comment]
> Hey @dusanbre Sorry for the delay, I tested this case locally, and yes, the issue can be solved when setting `NoLowerCase` and `NameReplacer`, but when setting that, you have to define the column tag for every model, otherwise, the DB fileds name will match the struct fields exactly, eg: the DB field: `restaurantId` => the struct field: `RestaurantId`. I created a PR for reference: https://github.com/goravel/example/pull/26/files.
> 
> 
> 
> And the `NamingStrategy` is:
> 
> 
> 
> ```
> 
> NamingStrategy: schema.NamingStrategy{
> 
> 	TablePrefix:   r.config.GetString(fmt.Sprintf("database.connections.%s.prefix", r.connection)),
> 
> 	SingularTable: r.config.GetBool(fmt.Sprintf("database.connections.%s.singular", r.connection)),
> 
> 	NoLowerCase:   true,
> 
> 	NameReplacer:  strings.NewReplacer("RestaurantId", "restaurantId", "CategoryId", "categoryId"),
> 
> },
> 
> ```
> 
> 
> 
> Are you eager to have this feature in v1.14? Otherwise, I'll add it in v1.15.

as far as I'm concerned, it's okay to add a feature in the new version, it's not necessary to fix it in the current one.

thank you

**Comment by hwbrzzl** [comment]
The new feature: add two new configurations for `NoLowerCase` and `NameReplacer`:

```
NamingStrategy: schema.NamingStrategy{
	TablePrefix:   r.config.GetString(fmt.Sprintf("database.connections.%s.prefix", r.connection)),
	SingularTable: r.config.GetBool(fmt.Sprintf("database.connections.%s.singular", r.connection)),
	NoLowerCase:   true,
	NameReplacer:  strings.NewReplacer("RestaurantId", "restaurantId", "CategoryId", "categoryId"),
},
```

**Comment by hwbrzzl** [comment]
Added `database.connections.{NAME}.name_replacer` and `database.connections.{NAME}.no_lower_case` configurations in v1.15
