### ISSUE TITLE
Add facades.Config.Set method

### ISSUE THREAD

**Issue by hwbrzzl** [goravel/goravel#48]
```
facades.Config.Set(map[string]any{
 "app.name": "local"
})
```

**Comment by sidshrivastav** [comment]
Hey @hwbrzzl, it this something you want to add in framework, I can see the Config interface but do you want to add it for Config?

**Comment by hwbrzzl** [comment]
Oh sorry @sidshrivastav , just missed this message. I reviewed this requirement and think just changing `Add(name string, configuration map[string]any)` to `Add(name string, configuration any)` in `contracts/config/config/go` is ok, then we can achieve:

```
facades.Config.Add("test", map[string]any{"a", "b"})
facades.Config.Get("test.a") // b
facades.Config.Add("test.test1", "c")
facades.Config.Get("test.test1") // c
```

**Comment by hwbrzzl** [comment]
If you have interesting in this, please take a look, thanks! @sidshrivastav

**Comment by sidshrivastav** [comment]
Sure, you can assign it to me. I'll work on it during the weekend.

**Comment by hwbrzzl** [comment]
Thanks! please enrich more unit tests like the above.

**Comment by hwbrzzl** [comment]
Hi @sidshrivastav , hope you have a great weekend.

FYI, we are going to release 1.10.0 in recent days, if there is a chance that merging this feature into master will be great.

There is the v1.10.0 upgrade guide:
<img width="689" alt="image" src="https://user-images.githubusercontent.com/24771476/224480145-40c887a9-4583-46a9-b305-f3a16af344c9.png">

**Comment by sidshrivastav** [comment]
I'll push the PR by tomorrow.
