### ISSUE TITLE
✨ [Feature] Bump to go1.23 and deprecate go1.21

### ISSUE THREAD

**Issue by devhaozi** [goravel/goravel#481]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

Go 1.23 has been released for 2 weeks, and Go 1.21 has reached EOL, see [https://endoflife.date/go](https://endoflife.date/go).

**Comment by hwbrzzl** [comment]
Good idea
