### ISSUE TITLE
✨ [Feature] Change the key type of ctx.WithValue to `any`

### ISSUE THREAD

**Issue by hwbrzzl** [goravel/goravel#486]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

The key type of `ctx.WithValue` is `string` now, it's not recommended, it's better to change it to `any`.

**Comment by mdanialr** [comment]
hi @hwbrzzl , thanks for submitting the issue i raised in telegram, when can i expect this change to be released?

**Comment by hwbrzzl** [comment]
In v1.15, still needs several months, welcome PR.

**Comment by kaifkh20** [comment]
can I work on this issue?

**Comment by mdanialr** [comment]
> can I work on this issue?

ah sorry just read this, i just do PR for this issue in [#628](https://github.com/goravel/framework/pull/628)

**Comment by hwbrzzl** [comment]
Thanks @kaifkh20 @mdanialr
