### ISSUE TITLE
✨ [Feature] chi http driver

### ISSUE THREAD

**Issue by devhaozi** [goravel/goravel#494]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

Support chi http driver

**Comment by devhaozi** [comment]
The basic logic is complete, But need to fix following issues:

- [ ] `Context` not work
- [ ] optimize performance
- [ ] implement middleware `Next()` method
- [ ] fix Response `Stream` method
- [ ] middleware's logic may have some problem
- [ ] fix tests

**Comment by hwbrzzl** [comment]
Good idea, but I wonder if there is a specific reason to support this driver officially? Because we have to update goravel/gin, goravel/fiber, and goravel/chi simultaneously when the Route/HTTP modules have any changes, and eliminate the differences between them.

**Comment by devhaozi** [comment]
> Good idea, but I wonder if there is a specific reason to support this driver officially? Because we have to update goravel/gin, goravel/fiber, and goravel/chi simultaneously when the Route/HTTP modules have any changes, and eliminate the differences between them, it's hard work.

Because chi is very lightweight, uses `net/http`, and has zero third-party dependencies. So it also has a lot of fans. I think we can support it.

**Comment by hwbrzzl** [comment]
Yes, it's a good package, but there is no user feedback that they need it for now, so I think we don't need to spend a lot of time on it, maybe future, but not now. Certainly, if you are interested in it, it's good to go. However, the framework may not provide official support when upgrading. It's too hard to upgrade three HTTP sub-package simultaneously for us for now.

**Comment by kkumar-gcc** [comment]
> Yes, it's a good package, but there is no user feedback that they need it for now, so I think we don't need to spend a lot of time on it, maybe future, but not now. Certainly, if you are interested in it, it's good to go. However, the framework may not provide official support when upgrading. It's too hard to upgrade three HTTP sub-package simultaneously for us for now.

agree!!
