### ISSUE TITLE
✨ [Feature] We need a middleware similar to gin.Recovery

### ISSUE THREAD

**Issue by zxdstyle** [goravel/goravel#497]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

When panic occurs, the process should not exit and the error should be captured and logged.

**Comment by zxdstyle** [comment]
Of course, this feature can be implemented with custom middleware, but I think this middleware should be built-in and enabled by default.

**Comment by devhaozi** [comment]
Fiber does not need to be modified, it was added previously.
