### ISSUE TITLE
✨ [Feature] maps.GetDeep

### ISSUE THREAD

**Issue by kadirgun** [goravel/goravel#498]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

A new function can be added to get the value we want from a nested map.

```go
data := map[string]interface{}{
	"first": map[string]interface{}{
		"second": map[string]interface{}{
			"third": map[string]interface{}{
				"key": "value",
			},
		},
	},
}

maps.GetDeep(data, "first.second.third.key")
```

**Comment by hwbrzzl** [comment]
It may be hard to do that, we need to make multiple assertions.
