### ISSUE TITLE
support migrate refresh, reset

### ISSUE THREAD

**Issue by alanreynosov** [goravel/goravel#50]
Enable refresh, reset and rollback options on migrate command

**Comment by hwbrzzl** [comment]
Thanks, good idea!

**Comment by kkumar-gcc** [comment]
Hi @hwbrzzl 
I want to work on this.

**Comment by hwbrzzl** [comment]
Thanks! We'll be better with your contributions!

**Comment by Maximo-Miranda** [comment]
hi, i'm new in the open source contribute, but i can help with this feature, what is the next steps ? send a pull request ?

**Comment by hwbrzzl** [comment]
Hi @Maximo-Miranda Welcome to contribute!

We already have a PR for this issue: https://github.com/goravel/framework/pull/77

That would be great if you can find another issue that you are interested in. 👍

**Comment by hwbrzzl** [comment]
> Hi @Maximo-Miranda Welcome to contribute!
> 
> We already have a PR for this issue: [goravel/framework#77](https://github.com/goravel/framework/pull/77)
> 
> That would be great if you can find another issue that you are interested in. 👍

This PR is out of date, feel free to pick up this issue if you have interesting.

**Comment by hwbrzzl** [comment]
There is a closed PR that can be referenced: https://github.com/goravel/framework/pull/77
