### ISSUE TITLE
🐛 [Bug] orm.Event 的GetAttribute无法获取 model id

### ISSUE THREAD

**Issue by zxdstyle** [goravel/goravel#503]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [ ] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

Linux

### Golang Version (Go 版本)

1.21.x

### Goravel Version (Goravel 版本)

1.14.7

### Describe The Problem (描述问题)

orm.Event 的GetAttribute无法获取 model id

### Reproduction Code (复现代码或截图)

<img width="408" alt="image" src="https://github.com/user-attachments/assets/5bf3236a-1b2a-49a2-bcbe-f66152f9291f">

**Comment by hwbrzzl** [comment]
Please try `event.GetAttribute("ID")`

**Comment by zxdstyle** [comment]
thank you
