### ISSUE TITLE
✨ [Feature] Route supports configure timeout

### ISSUE THREAD

**Issue by hwbrzzl** [goravel/goravel#504]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

1. A global configuration;
2. Add a new `WithContext` method for `ctx.Request()`, the new ctx is generated by `context.WithTimeout`, then the new method can be called in a middleware;

**Comment by KlassnayaAfrodita** [comment]
hi, I'm new to goravel and would like to take this problem. Could you describe it in more detail?

**Comment by KlassnayaAfrodita** [comment]
check my changes

**Comment by KlassnayaAfrodita** [comment]
what else needs to be done in this issues

**Comment by KlassnayaAfrodita** [comment]
do I understand correctly that the errors that the tests give are not related to my code changes? Am I right or wrong?
