### ISSUE TITLE
✨ [Feature] Upgrade Redis to v9 for goravel/redis

### ISSUE THREAD

**Issue by hwbrzzl** [goravel/goravel#506]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

Now is v8, upgrade it to v9.

**Comment by YlanzinhoY** [comment]
I send my PR in goravel/redis

**Comment by hwbrzzl** [comment]
Thanks @YlanzinhoY Adde you to the contributor list.
