### ISSUE TITLE
🐛 [Bug] Call RefreshDatabase and Artisan run migrate from  the Test file return error

### ISSUE THREAD

**Issue by caturandi-labs** [goravel/goravel#509]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [ ] The problem can be stably reproduced (这个问题可以被稳定复现)
- [ ] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

MacOS

### Golang Version (Go 版本)

1.21.x

### Goravel Version (Goravel 版本)

1.14.7

### Describe The Problem (描述问题)

Hi I create feature testing for some features in my app. The idea is I wanted to refresh database / run artisan migrate when run the test script. But I got this error :

```
=== RUN   TestAuthControllerTestSuite/TestLoginValidationRequest
    application.go:88: test panicked: failed to open source, "file://./database/migrations": open .: no such file or directory
        goroutine 9 [running]:
```

Any idea on this?

### Reproduction Code (复现代码或截图)

```go
// SetupTest will run before each test in the suite.
func (s *AuthControllerTestSuite) SetupTest() {
	s.RefreshDatabase()
        facades.Artisan().Call("migrate:fresh")
}
```

**Comment by hwbrzzl** [comment]
Could you try this case in your local? https://github.com/goravel/example/blob/master/tests/services/main_test.go

**Comment by hwbrzzl** [comment]
Could you create a PR for your failed case to goravel/example? The test cases of goravel/example are tested by CI, they should pass. Not sure what's happening in your local.
