### ISSUE TITLE
Generate a docker-compose.yml file

### ISSUE THREAD

**Issue by hwbrzzl** [goravel/goravel#51]

**Comment by predatorprasad** [comment]
can you elaborate on it.

**Comment by hwbrzzl** [comment]
Just generate a simple `docker-compose.yml` file based on [Dockerfile](https://github.com/goravel/goravel/blob/v1.9.x/Dockerfile) and we can run it normally.

Nothing special, please feel free to take it if you have interesting. 😃

**Comment by predatorprasad** [comment]
I have submitted a PR #52
