### ISSUE TITLE
🐛 [Bug] S3 driver url bug

### ISSUE THREAD

**Issue by dusanbre** [goravel/goravel#518]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [X] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

MacOS

### Golang Version (Go 版本)

1.21.x

### Goravel Version (Goravel 版本)

1.14.7

### Describe The Problem (描述问题)

![Screenshot 2024-11-05 at 12 00 08](https://github.com/user-attachments/assets/b5771433-1445-4703-b4fb-0d6ce1d1815d)

When you creating new client instance you should pass AWS_URL as ENDPOINT i think.
If you dont do that it will fallback to default, which would be amazonaws.com, but i am using backblaze.com so this will not work.

### Reproduction Code (复现代码或截图)

```go

func NewS3(ctx context.Context, config config.Config, disk string) (*S3, error) {
	accessKeyId := config.GetString(fmt.Sprintf("filesystems.disks.%s.key", disk))
	accessKeySecret := config.GetString(fmt.Sprintf("filesystems.disks.%s.secret", disk))
	region := config.GetString(fmt.Sprintf("filesystems.disks.%s.region", disk))
	bucket := config.GetString(fmt.Sprintf("filesystems.disks.%s.bucket", disk))
	url := config.GetString(fmt.Sprintf("filesystems.disks.%s.url", disk))
	if accessKeyId == "" || accessKeySecret == "" || region == "" || bucket == "" || url == "" {
		return nil, fmt.Errorf("please set %s configuration first", disk)
	}

	client := s3.New(s3.Options{
		Region:      region,
		Credentials: aws.NewCredentialsCache(credentials.NewStaticCredentialsProvider(accessKeyId, accessKeySecret, "")),
                BaseEndpoint: aws.String(url),
	})

	return &S3{
		ctx:      ctx,
		config:   config,
		disk:     disk,
		instance: client,
		bucket:   bucket,
		url:      url,
	}, nil
}

```

**Comment by hwbrzzl** [comment]
Thanks, I'll test it and release a new version.

**Comment by hwbrzzl** [comment]
Hi @dusanbre I tested this, I think `AWS_URL` can't be set to `BaseEndpoint` directly. Because the default s3 link is `https://{BUCKET}.s3.us-east-2.amazonaws.com`, it's combined by `BUCKET` and `BaseEndpoint`, so `BaseEndpoint=s3.us-east-2.amazonaws.com`. If we set `AWS_URL` to `BaseEndpoint`, the default s3 link will be: `https://{BUCKET}.{AWS_URL}`, it's unexpected. 

And I think the AWS domain is only returned using the `TemporaryUrl` method, do you want to replace the temporary URL(the AWS domain part) with backblaze.com? If so, adding a new configuration(s3.temporary_url) and using it when calling the `TemporaryUrl` method should be good.

**Comment by dusanbre** [comment]
local.debug: operation error S3: ListObjectsV2, https response error StatusCode: 0, RequestID: , HostID: , request send failed, Get "https://nibblo-prd.s3.eu-central-003.amazonaws.com/?delimiter=%2F&list-type=2&prefix=": dial tcp: lookup nibblo-prd.s3.eu-central-003.amazonaws.com on 127.0.0.11:53: no such host

Here is the error, just to be clear. Btw i move code from package to my repo and add this BaseEndpoint as aws.String(url) and its working for me. The other way i did not found. I also try with temp url but its not working.

https://www.backblaze.com/docs/cloud-storage-use-the-aws-sdk-for-go-with-backblaze-b2
Here is the link as a reference.

As far as I'm concerned, you don't have to implement this, I managed to create a workaround.

**Comment by hwbrzzl** [comment]
Great 👍
