### ISSUE TITLE
🐛 [Bug] Error: Unable to render template when using Jet engine through Fiber V2

### ISSUE THREAD

**Issue by quocduongpy** [goravel/goravel#520]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [X] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

Windows

### Golang Version (Go 版本)

1.21.x

### Goravel Version (Goravel 版本)

 v1.14.7

### Describe The Problem (描述问题)

"Error: Unable to render template when using Jet engine through Fiber V2.

I’ve confirmed that the index.jet file is created in the correct directory."

go version go1.23.2 windows/amd64
`
panic: failed to render: render: template admin/index.jet could not be Loaded: template /admin/index.jet could not be found

goroutine 83 [running]:
github.com/goravel/fiber.(*Route).GlobalMiddleware.Cors.func1({0x300c4d8, 0xc0007ba018})
        C:/Users/Admin/go/pkg/mod/github.com/goravel/fiber@v1.2.4/cors.go:51 +0x428
github.com/goravel/fiber.(*Route).GlobalMiddleware.middlewareToFiberHandler.func2(0x207a3a0?)
        C:/Users/Admin/go/pkg/mod/github.com/goravel/fiber@v1.2.4/utils.go:36 +0x26
github.com/gofiber/fiber/v2.(*App).next(0xc000b60008, 0xc000a58608)
        C:/Users/Admin/go/pkg/mod/github.com/gofiber/fiber/v2@v2.52.5/router.go:145 +0x1be
github.com/gofiber/fiber/v2.(*App).handler(0xc000b60008, 0x48302f?)
        C:/Users/Admin/go/pkg/mod/github.com/gofiber/fiber/v2@v2.52.5/router.go:172 +0x69
github.com/valyala/fasthttp.(*Server).serveConn(0xc000dd4d88, {0x300c910, 0xc000120748})
        C:/Users/Admin/go/pkg/mod/github.com/valyala/fasthttp@v1.55.0/server.go:2379 +0xe70
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc000616000, 0xc00073b7c0)
        C:/Users/Admin/go/pkg/mod/github.com/valyala/fasthttp@v1.55.0/workerpool.go:224 +0x91
github.com/valyala/fasthttp.(*workerPool).getCh.func1()
        C:/Users/Admin/go/pkg/mod/github.com/valyala/fasthttp@v1.55.0/workerpool.go:196 +0x32
created by github.com/valyala/fasthttp.(*workerPool).getCh in goroutine 64
        C:/Users/Admin/go/pkg/mod/github.com/valyala/fasthttp@v1.55.0/workerpool.go:195 +0x190`

### Reproduction Code (复现代码或截图)

```go
//http.go
"fiber": map[string]any{
				// prefork mode, see https://docs.gofiber.io/api/fiber/#config
				"prefork": false,
				// Optional, default is 4096 KB
				"body_limit":   4096,
				"header_limit": 4096,
				"route": func() (route.Route, error) {
					return fiberfacades.Route("fiber"), nil
				},
				// Optional, default is "html/template"
				"template": func() (fiber.Views, error) {
					return jet.New("./resources/views", ".jet"), nil
				},
			},


```

**Comment by hwbrzzl** [comment]
Could you commit a PR to goravel/example to reproduce this issue? I'll try it.

**Comment by quocduongpy** [comment]
> Could you commit a PR to goravel/example to reproduce this issue? I'll try it.

I'll create a pull request for you soon.

**Comment by quocduongpy** [comment]
I had some time to check the error, and I realized that the issue was caused by my mistake when I used Make("web/index.jet") instead of Make("web/index"). Everything is working well now. Thanks!

**Comment by hwbrzzl** [comment]
Great 👍
