### ISSUE TITLE
✨ [Feature] User can custom recover when a request panic

### ISSUE THREAD

**Issue by hwbrzzl** [goravel/goravel#521]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

Add a custom function to gin and fiber configurations.

**Comment by KlassnayaAfrodita** [comment]
can I take this issue?

**Comment by hwbrzzl** [comment]
Sure, please, thanks!

**Comment by KlassnayaAfrodita** [comment]
> Sure, please, thanks!

could you please give the details of the task?

**Comment by hwbrzzl** [comment]
I think we can add a new `Recover` method in https://github.com/goravel/framework/blob/master/contracts/route/route.go#L12, it contains a func variable. Then implement it in goravel gin/fiber and use it in:

https://github.com/goravel/fiber/blob/master/route.go#L110
https://github.com/goravel/fiber/blob/master/middleware_timeout.go#L29
https://github.com/goravel/gin/blob/master/middleware_timeout.go#L30
https://github.com/goravel/gin/blob/master/route.go#L34

**Comment by KlassnayaAfrodita** [comment]
my suggestions are as follows:
```
// contracts/route/route.go
type Route interface {
    // ...
    Recover(recoverFunc func(ctx Context, err interface{}))
}

// gin/route.go
func (r *Route) Recover(recoverFunc func(ctx *gin.Context, err interface{})) {
    r.recoverFunc = recoverFunc
}

// В middleware_timeout.go
defer func() {
    if err := recover(); err != nil {
        if r.recoverFunc != nil {
            r.recoverFunc(ctx, err)
        } else {
            ...
        }
    }
}()
```
what do you think?

**Comment by hwbrzzl** [comment]
Basically, looks good, and we need to replace [this method](https://github.com/goravel/gin/blob/master/route.go#L34) if setting `recoverFunc`.
