### ISSUE TITLE
🐛 [Bug] Too many connections to DB on gRPC

### ISSUE THREAD

**Issue by MissaelAnda** [goravel/goravel#522]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [ ] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

MacOS

### Golang Version (Go 版本)

1.21.x

### Goravel Version (Goravel 版本)

v1.14.7

### Describe The Problem (描述问题)

I created a gRPC service and added it to the main.go file, it works great when using single requests from something like grpcurl or postman client, but I wanted to stress test it with ghz with 1,000 connections and 10,000 requests but postgresql panics after reaching the max_connections:

```
failed to connect to `host=127.0.0.1 user=postgres database=database`: server error (FATAL: sorry, too many clients already (SQLSTATE 53300))
```

### Reproduction Code (复现代码或截图)

Create a gRPC service and inside the implementation code do something with the database:

```go
func (c *GrpcService) Update(ctx context.Context, request *protos.Request) (*protos.Response, error) {
    // ...
    err := facades.Orm().Query().Create(&user)
    // ...
}
```

**Comment by hwbrzzl** [comment]
If the connect number is over the max_connections configuration, the error will be thrown, you can try to increase the max_connections configuration.

**Comment by hwbrzzl** [comment]
What' the concurrent in this situation (psql 100, max_open_cons 50/80)? I checked it locally and did not reproduce it.

**Comment by MissaelAnda** [comment]
I retried this and it still failed but I don't know have the time to debug it and don't know why it fails.
If someone else has the same problem please reopen this issue.
