### ISSUE TITLE
🐛 [Bug] Request body validation for DELETE method

### ISSUE THREAD

**Issue by dusanbre** [goravel/goravel#530]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [ ] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

MacOS

### Golang Version (Go 版本)

1.21.x

### Goravel Version (Goravel 版本)

1.23.3

### Describe The Problem (描述问题)

When i try to validate DELETE /{someroute} with json body params, i always get validation errors. 
It is like validator not picking up values from body when method is DELETE.

### Reproduction Code (复现代码或截图)

```go
//Controller
validator, err := ctx.Request().Validate(map[string]string{
		"userId":       "required",
		"restaurantId": "required",
	})

DELETE /like/rest
body 
{
  "userId": 6,
  "restaurantId": 26
}

// Response
{
  "errors": {
    "restaurantId": {
      "required": "restaurantId is required to not be empty"
    },
    "userId": {
      "required": "userId is required to not be empty"
    }
  }
}

```

**Comment by hwbrzzl** [comment]
Based on [the validate package logic](https://github.com/gookit/validate/blob/master/validate.go#L353-L356), the DELETE request should not contain body, you can use POST instead.
