### ISSUE TITLE
✨ [Feature] Find a fixed/unified way to generate mock files instead of using mockery directly

### ISSUE THREAD

**Issue by hwbrzzl** [goravel/goravel#538]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

When mockery is upgraded, there may be a lot of modification. If framework upgrades mockery, contributors have to upgrade it as well, find a fixed/unified way to generate mock files, let framework controller the mockery version.

**Comment by almas1992** [comment]
There is a problem here. The framework project does not have a `main.go`, so it is not possible to execute the artisan command.

**Comment by hwbrzzl** [comment]
Make sense, we may create a shell file to run it.

**Comment by hwbrzzl** [comment]
This can be solved in go 1.24: `go tool`: https://tip.golang.org/doc/go1.24
