### ISSUE TITLE
怎么获取一个redis实例呢

### ISSUE THREAD

**Issue by netwu** [goravel/goravel#6]
怎么获取一个redis实例呢

**Comment by hwbrzzl** [comment]
`config/cache.go` 中设置 `default` 为 `redis`, 然后使用 `facades.Cache` 即可，详见文档：[缓存系统](https://www.goravel.dev/cn/zong-he-hua-ti/huan-cun-xi-tong)

**Comment by netwu** [comment]
> `config/cache.go` 中设置 `default` 为 `redis`, 然后使用 `facades.Cache` 即可，详见文档：[缓存系统](https://www.goravel.dev/cn/zong-he-hua-ti/huan-cun-xi-tong)

我想使用redis的原生命令怎么用呢，比如lpush,rpop

**Comment by hwbrzzl** [comment]
可以这样
```
package routes

import (
  "fmt"
  "time"

  "github.com/gin-gonic/gin"
  "github.com/go-redis/redis/v8"
  "github.com/goravel/framework/support/facades"
)

func Web() {
  facades.Route.GET("/", func(ctx *gin.Context) {
    client := redis.NewClient(&redis.Options{
      Addr:     fmt.Sprintf("%s:%s", facades.Config.GetString("database.redis.default.host"), facades.Config.GetString("database.redis.default.port")),
      Password: facades.Config.GetString("database.redis.default.password"),
      DB:       facades.Config.GetInt("database.redis.default.database"),
    })

    client.Set(ctx, "goravel", "redis", time.Minute)
  })
}
```

**Comment by netwu** [comment]
> 可以这样
> 
> ```
> package routes
> 
> import (
>   "fmt"
>   "time"
> 
>   "github.com/gin-gonic/gin"
>   "github.com/go-redis/redis/v8"
>   "github.com/goravel/framework/support/facades"
> )
> 
> func Web() {
>   facades.Route.GET("/", func(ctx *gin.Context) {
>     client := redis.NewClient(&redis.Options{
>       Addr:     fmt.Sprintf("%s:%s", facades.Config.GetString("database.redis.default.host"), facades.Config.GetString("database.redis.default.port")),
>       Password: facades.Config.GetString("database.redis.default.password"),
>       DB:       facades.Config.GetInt("database.redis.default.database"),
>     })
> 
>     client.Set(ctx, "goravel", "redis", time.Minute)
>   })
> }
> ```

这样也没问题，但是不太优雅

**Comment by hwbrzzl** [comment]
嗯，的确，逐步优化下，目前来说可以封装个 helper 先用
