### ISSUE TITLE
Model Accesors and Mutators

### ISSUE THREAD

**Issue by alanreynosov** [goravel/goravel#61]
Enable usage of model Accessors and Mutators to modify model attributes before to be stored to DB or returning query results

**Comment by hwbrzzl** [comment]
Hi @alanreynosov . You can use Gorm Hook to achieve this function: [the document](https://gorm.io/zh_CN/docs/hooks.html). But I haven't figured out whether this method is suitable for Goravel. You can use Gorm hook first if you need.
