### ISSUE TITLE
Guideance : how to return several model associations?

### ISSUE THREAD

**Issue by alanreynosov** [goravel/goravel#64]
having this model

```
type Player struct {
	orm.Model
	User         *User
	UserID       string
	ClubId       string
	Club         *Club
	FirstName    string
	LastName     string
	PlayerTypeID string
	PlayerType   *PlayerType
	Street       string
	City         string
	PostalCode   string
	Country      string
	ContactName  string
	ContactPhone string
}
```

with at least 3 models associated

At the moment of create the User also create the player

so I can get the values of User querying player

```	player.User = user

	facades.Orm.Query().Select(orm.Associations).Create(&player)

	facades.Orm.Query().Model(&player).Association("User").Find(&player)

	ctx.Response().Json(http.StatusOK, contractshttp.Json{
		"message": "User saved",
		"data":    &player,
		"action":  action,
	})
```
------
```
 http -f POST localhost:3000/users name="user3" password="1234" player_type_id=1 first_name="pepe" last_name="dsads" club_id=8 country="mexico" street="dasdasda" postal_code="dasda" contact_phone="sdas" contact_name="dasdas"  email="ejase@gmaiddbn.com"
HTTP/1.1 200 OK
Content-Length: 844
Content-Type: application/json; charset=utf-8
Date: Tue, 07 Mar 2023 01:12:35 GMT
Vary: Origin

{
    "action": "create",
    "data": {
        "City": "",
        "Club": {
            "City": "",
            "ContactEmail": "",
            "ContactName": "",
            "ContactPhone": "",
            "Country": "",
            "CreatedAt": "0001-01-01T00:00:00Z",
            "Description": "",
            "ID": 8,
            "Name": "",
            "Organization": null,
            "OrganizationId": "",
            "PostalCode": "",
            "Street": "",
            "UpdatedAt": "0001-01-01T00:00:00Z"
        },
        "ClubId": "8",
        "ContactName": "dasdas",
        "ContactPhone": "sdas",
        "Country": "mexico",
        "CreatedAt": "0001-01-01T00:00:00Z",
        "FirstName": "pepe",
        "ID": 0,
        "LastName": "dsads",
        "PlayerType": null,
        "PlayerTypeID": "1",
        "PostalCode": "dasda",
        "Street": "dasdasda",
        "UpdatedAt": "0001-01-01T00:00:00Z",
        "User": {
            "Avatar": "",
            "CreatedAt": "2023-03-07T01:12:35.702Z",
            "DeletedAt": null,
            "Email": "ejase@gmaiddbn.com",
            "ID": 57,
            "Name": "user3",
            "Password": "$2a$10$VtamLUPqCvHlfBlwEOpzKOGhqyuE9vcjPjRc6y8QuCLoGNgkLoSTG",
            "UpdatedAt": "2023-03-07T01:12:35.702Z"
        },
        "UserID": "57"
    },
    "message": "User saved"
}
```

everything looks good to here

however, when I want to also associate model club or player_type only returns associated values, I would need to query those models separatedly so the associated models can populate player model and return belonging results, 

I tried instantiating those models and assign ID value, and yet brings empty object from model, my expectation here is the ORM query joins given the association and ID, and only works querying each model separatedly, is my expectation realistic (I used to do it like this in laravel) or I am missing something?

**Comment by hwbrzzl** [comment]
Sorry, I'm not clear about your question, can you show your expected code?

**Comment by iconmedios-dev** [comment]
Sure, let me clear.

How to make a query for **player** that shows other multiple associations, In the example works with **user** because user is created and hydrated in the same code block, but in the case of "club" and "player_types" are returned as null.

**Comment by alanreynosov** [comment]
also, is there any equivalent feature as _protectedProperties_ ? in order to prevent to display sensitive data as user.password as example

**Comment by alanreynosov** [comment]
iconmedios-dev is also me, different PC

**Comment by hwbrzzl** [comment]
You want to load `user`, `club`, `player_types` to `player` at the same time, right? You can try below:
```
facades.Orm.Query().With("User").With("Club").With("PlayerType").Find(&player)
```

[The document](https://www.goravel.dev/ORM/relationships.html#eager-loading-multiple-relationships)

**Comment by alanreynosov** [comment]
just like laravel, awesome!!, thanks so much

about the model _protectedProperties_ is there something ?

**Comment by hwbrzzl** [comment]
> just like laravel, awesome!!, thanks so much
> 
> about the model _protectedProperties_ is there something ?

Like below:

```
type User struct {
  Name string `gorm:"-"`
}
```

**Comment by alanreynosov** [comment]
Awesome, much appreciated
