### ISSUE TITLE
✨ [Feature] Database Seeding function

### ISSUE THREAD

**Issue by hwbrzzl** [goravel/goravel#66]

**Comment by DevHaoZi** [comment]
Also need factory.

**Comment by kkumar-gcc** [comment]
@hwbrzzl I would like to work on this issue.

**Comment by hwbrzzl** [comment]
Thanks, please, Let us implement it like Laravel. Welcome back @kkumar-gcc.

**Comment by kkumar-gcc** [comment]
> Thanks, please, Let us implement it like Laravel. Welcome back @kkumar-gcc.

Okay, thanks
