### ISSUE TITLE
✨ [Feature] Missing testing in documentations

### ISSUE THREAD

**Issue by vortechron** [goravel/goravel#71]
Theres no example for how to do feature testing like laravel in documentation such as asserting database content, etc..

Thanks, nice project!

**Comment by hwbrzzl** [comment]
Thanks for your issue, I'll make an example.

**Comment by vortechron** [comment]
@hwbrzzl thank you.. i saw a glimpse of e2e testing example on https://www.goravel.dev/the-basics/routing.html#testing-routing , but i think that example is a bit misleading becauses you need to boot the app first right?

**Comment by hwbrzzl** [comment]
Yes, actually, the mock is to do this work and can do it better. `facades.*` are interface, the mock will implement the interface and we will set `facades.*=mock`, it's similar to container/dependency injection. The mock has many useful functions that can help us build the unit tests.

**Comment by hwbrzzl** [comment]
[For Mock Detail](https://github.com/stretchr/testify)

**Comment by vortechron** [comment]
i think maybe thats y its slow at the build time because of facades.* global variables, maybe just resolve the instance as function when we need/use it?

**Comment by hwbrzzl** [comment]
Yes, If you didn't use some facades, you can remove them in `config/app.go::providers`, then you'll build faster, and the volume will be smaller.

**Comment by hwbrzzl** [comment]
I added an example [here](https://github.com/goravel/example#testing-with-mock).

**Comment by vortechron** [comment]
@hwbrzzl hi tq for the updates, but i cant find endpoint testing with db assertion 

quick example in laravel:
```
$r = $this->post('/users', ['name' => 'test']);
$r->assertOk();

$this->assertDatabaseHas('users', ['name' => 'test']);
```

**Comment by hwbrzzl** [comment]
Yes, it's better, we have a plan to implement this, but we haven't. Welcome to PR!

**Comment by hwbrzzl** [comment]
We will solve this issue on https://github.com/goravel/goravel/issues/73.
