### ISSUE TITLE
make command supports subdirectory 

### ISSUE THREAD

**Issue by hwbrzzl** [goravel/goravel#72]
Such as:
```
go run . artisan make:controller admin/LoginController
```

We need to add subdirectory support for all make commands.

**Comment by dragoonchang** [comment]
I would like to contribute to Goravel, and addressing this small issue might be a great starting point.

From my understanding, the example command generates:
- a file with the correct path
- an incorrect file name: _login_controller.go should be changed to login_controller.go
- an incorrect package name, as well as unnecessary prefix paths for types and functions
- also need to take care of multi directories scienario.

The current generated code is:
`package controllers

import (
	"github.com/goravel/framework/contracts/http"
)

type Admin/LoginController struct {
	//Dependent services
}

func NewAdmin/LoginController() *Admin/LoginController {
	return &Admin/LoginController{
		//Inject services
	}
}

func (r *Admin/LoginController) Index(ctx http.Context) {
}
`

It should be changed to the following:
`package admin

import (
	"github.com/goravel/framework/contracts/http"
)

type LoginController struct {
	//Dependent services
}

func NewLoginController() *LoginController {
	return &LoginController{
		//Inject services
	}
}

func (r *LoginController) Index(ctx http.Context) {
}
`

If I have made any mistakes, please let me know. If everything is clear, then I could push a PR to fix this issue. Thanks.

**Comment by hwbrzzl** [comment]
Hi, @dragoonchang Welcome to contribute, but this issue already has a PR that reviewing: https://github.com/goravel/framework/pull/80

Can you find another issue to deal with? Thanks!

**Comment by dragoonchang** [comment]
Got it. Let me try to find another one.

**Comment by DevHaoZi** [comment]
Another command `make:request` think should also support this feature.

**Comment by hwbrzzl** [comment]
Yes, all of make commands need to support subdirectory.

**Comment by hwbrzzl** [comment]
> Hi, @dragoonchang Welcome to contribute, but this issue already has a PR that reviewing: [goravel/framework#80](https://github.com/goravel/framework/pull/80)
> 
> Can you find another issue to deal with? Thanks!

This PR is out of date, feel free to pick up this issue if you have interesting.

**Comment by hwbrzzl** [comment]
There is a closed PR that can be referenced: https://github.com/goravel/framework/pull/80
