### ISSUE TITLE
✨ [Feature] Optimize the test experience when using configuration

### ISSUE THREAD

**Issue by hwbrzzl** [goravel/goravel#73]
Like: https://laravel.com/docs/10.x/testing

**Comment by mauri870** [comment]
This article describes an [interesting solution for integration tests](https://www.twilio.com/blog/get-started-testing-api-built-with-golang)

We could have our own TestMain that does setup (migrate, seed), spawns the server in a goroutine, runs the tests and then a teardown at the end (refresh database for example)
