### ISSUE TITLE
Request to add hooks in ORM

### ISSUE THREAD

**Issue by yueqing2617** [goravel/goravel#79]
Hi,

I would like to suggest adding some hooks to the ORM in Goravel. Specifically, I would like to see the following hooks added:

BeforeSave
BeforeCreate
AfterCreate
AfterSave
I frequently use these hooks in my business logic, and I believe they would be valuable additions to the ORM.

Thank you for considering my request!

**Comment by hwbrzzl** [comment]
Hi @yueqing2617 , thanks for your suggestion. Yes, we'll have it, maybe in the next version!

**Comment by hwbrzzl** [comment]
Please look into #61
