### ISSUE TITLE
Support NoRoute and NoMethod in facades.Route

### ISSUE THREAD

**Issue by hwbrzzl** [goravel/goravel#86]
Just like: https://laravel.com/docs/9.x/routing#fallback-routes

**Comment by dragoonchang** [comment]
Could you provide some use cases?

**Comment by hwbrzzl** [comment]
Thanks! But I'm working on this and will create a PR today. You can check the assignees to confirm if there is someone working on this.

**Comment by hwbrzzl** [comment]
Emm, or I can add a new label to tag it.

**Comment by hwbrzzl** [comment]
Added a processing label

**Comment by hwbrzzl** [comment]
Do you have any interest in this? https://github.com/goravel/goravel/issues/48 
I think the staff hasn't started dealing with it, it had stood a long time.

**Comment by dragoonchang** [comment]
Let me read this https://github.com/goravel/goravel/issues/48 first, it looks good to me. Thanks.
