### ISSUE TITLE
Support gorm.Expr

### ISSUE THREAD

**Issue by hwbrzzl** [goravel/goravel#91]

**Comment by dragoonchang** [comment]
Hi Wenbo, can you provide some use cases? I understand the syntax of gorm.Expr(), but I have no idea how to integrate with Goravel.

**Comment by hwbrzzl** [comment]
Hey @dragoonchang We want to implement like below:
```
db.Model(&product).Update("price", db.Raw("price * ? + ?", 2, 100))
```

`db.Raw` can be an alias of `gorm.Expr`. About why we use `db.Raw`, we want to be consistent with Laravel. We can add a `database.db` directory in goravel/framework.

Any other good ideas are welcome!

**Comment by dragoonchang** [comment]
Thanks, it's much clear now. 

I still don't understand one thing, from the test case below, the new func Raw() looks more natural to be placed under contracts/database/orm/Query instead of the new database.db directory.

I am glad to hear you sharing to help me understand Goravel better!

```golang
func (s *GormQueryTestSuite) TestUpdate() {
	for driver, query := range s.queries {
		s.Run(driver.String(), func() {
			user := User{Name: "update_user", Avatar: "update_avatar"}
			s.Nil(query.Create(&user))
			s.True(user.ID > 0)

			user.Name = "update_user1"
			s.Nil(query.Save(&user))
			s.Nil(query.Model(&User{}).Where("id = ?", user.ID).Update("avatar", "update_avatar1"))
			// s.Nil(query.Model(&User{}).Where("id = ?", user.ID).Update("avatar", query.Raw("update_avatar1")))

			var user1 User
			s.Nil(query.Find(&user1, user.ID))
			s.Equal("update_user1", user1.Name)
			s.Equal("update_avatar1", user1.Avatar)
		})
	}
}
```

**Comment by hwbrzzl** [comment]
`contracts/database/orm/Query` contains all methods of `facades.Orm.Query()`, there is a `Raw` method belonging to Orm, the action of this method is to run a SQL directly, it's unexpected to use `facades.Orm.Query().Raw()` to resolve this issue. I think `db.Raw()` is more precise and consistent with Laravel.
