### ISSUE TITLE
✨ [Feature] facades.Route supports fiber driver like gin

### ISSUE THREAD

**Issue by hwbrzzl** [goravel/goravel#93]

**Comment by DevHaoZi** [comment]
I see you removed the breaking change tag, do we just replacing Gin with fiber?
cc @hwbrzzl.

**Comment by hwbrzzl** [comment]
No ~ we can just create a new fiber driver for the Route module, like goravel/s3, it shouldn't be a breaking change.

**Comment by DevHaoZi** [comment]
> No ~ we can just create a new fiber driver for the Route module, like goravel/s3, it shouldn't be a breaking change.

ok, let me see how to implement it.

**Comment by DevHaoZi** [comment]
The fiber driver is almost complete, but I have a problem on getting input. I am temporarily busy with other items and need someone to help fix it.
![image](https://github.com/goravel/goravel/assets/115467771/cc6c9915-7284-4c00-a046-12f974c0365f)

**Comment by hwbrzzl** [comment]
Do not hurry, just fix it when you have time. 👍

**Comment by DevHaoZi** [comment]
Done.
